### ISSUE TITLE
Predefined segment name (tag) lists

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#10]
Currently the app supports loading a set of predefined segment names from the /resources/tags/default.tag file. 

Add support for reading an [optional] second file that is associated with the pen data file being loaded, and using this file to also provide predefined segment names. 
#### Note: Requirements have been updated here to reflect discussion to date
- When loading a supported input pen data file (*.xml or *.txyp), ex: 'pen_dat.txt', check for the existence of a file in the same directory with the same name as the input file, but with a different file extension, ex: 'pen_dat.txt'. The segment name list file extension can be anything but valid MarkWrite input file extensions or the MarkWrite project file extension.
- If matching file(s) are found, select the first on and treat it as the associated segment name list file
- Parse the associated segment name list file.
- Given the example file names used here, the full list of predefined segment names should =   pen_dat.txt generated list + default.tag generated list

**Comment by Mark-Torrance** [comment]
I would prefer not to change file extensions. This is partly because it will confuse users ("I don't know what and ep file is? How do I open it? etc") Can we not just require that the segment tag lists have “_taglist” as part of their filename then check on opening a data file that the file that they are trying to open doesn’t contain “_taglist”? This avoids both renaming and committing to particular extensions.

**Comment by Mark-Torrance** [comment]
Sol: 

> Remember that the open file dialog chooser filters the files that a user can see / select based on file 
> extension so only supported pen data input files or saved WriteMark project files can be selected. 
> This can only be done based on file extension.

Ah, I didn’t realise this. Yes, change file extensions on data files to indicate format. So epfile.txt -> epfile.ep. 

My only concern about this is that it makes the time,x,y,pressure format look like some proprietory eye and pen format rather than just generic digitiser capture. Guido’s data looks the same (I think) and so will data captured via PsychoPy if we get it working. I would like to avoid naming eye and pen within the program. Silly politics, I know, but sometimes it’s best not to antagonise people.

So maybe epfile.txt -> epfile.txyp  where .txyp represents the generic format?

Mark

**Comment by isolver** [comment]
> I would prefer not to change file extensions. This is partly because it
> will confuse users ("I don't know what and ep file is? How do I open it?
> etc")

We could do this, but I see doing this as more confusing / error prone then
using meaningful file extensions.  This is because:
- still leaves people opening invalid files by mistake (how is someone
  to know not to pick xxxx_tag.txt files)
- removes the ability to associate supported pen data input file types
  with the WriteMark app when we add the app installer, so a user can double
  click a file and have WriteMark automatically open it. So a user does not
  need to 'know' what a '.xxxx' file is. (as an analogy, people do not need
  to know what a '.xls' file is, they can just double click it and Excel or
  LibreOffice will start and load the file.

That is why I was leaning toward the EP input file using an extension other
than '.txt', and for that matter not using '.xml' for the other supported
format.

I've delivered my reasoning here. You now tell me what to do and I will not
debate it further. ;)

**Comment by Mark-Torrance** [comment]
Sorry, crossed emails. I agree with you, but with caveats.

**Comment by isolver** [comment]
From Mark:

> So maybe epfile.txt -> epfile.txyp where .txyp represents the generic format?

I like this idea. Then, when we do the windows installer for the MarkWrite app folder, we can associate '.txyp' extension with the app exe.

Should this apply to the EP data files and the .xml data files as well? I can determine which format to parse from the first line of the file.

**Comment by Mark-Torrance** [comment]
> Should this apply to the EP data files and the .xml data files as well? I can determine which format to parse from the first line of the file.

I suggest that you accept both .xml (for file in HandSpy format) and .txyp file extension (for all other files, which must have t,x,y,p format). So leave the xml extension, but require users to name their txyp files with .txyp before they can be used by the program.

**Comment by isolver** [comment]
On Thu, Apr 9, 2015 at 10:35 AM, Mark-Torrance notifications@github.com
wrote:

> So leave the xml extension, but require users to name their txyp files
> with .txyp before they can be used by the

Sounds good. The data importer classes already have a validate() method
that is called when a file is selected, but before it is fully read. For
the XmlImporter, it ensures the file contents is using the HandSpy schema.
So if a user opens some other arbitrary .xml file, it will not load and
they get an error dialog.

**Comment by Mark-Torrance** [comment]
There's actually an XML standard for digitiser data. It's possible that that the handspy files use this. I vaguely remember talk about it when they were developing the software. I've done a quick google though and I can't find the relevant page.

**Comment by isolver** [comment]
Implemented as per updated logic requirements in initial post for this issue. The full predefined segment name list is then used to populate the 'Create Segment Dialog' text entry dropdown list. 

There is missing functionality based on my memory of requirement discussion yesterday:
- no tracking is done of what the last selected index in the segment name list was
- segment name in create segment dialog does not default to one of the predefined names in the list

I'm not going to implement the above right now because I am not sure the current Create Segment Dialog gui is what we really need for this. I will open a new issue giving the above 2 outstanding requirements.
