### ISSUE TITLE
Modify pen sample status field value combinations

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#108]
From Mark:

Sorry to return to this again. Can we simplify things further by specifying PRESS and HOVER for all PRESS and HOVER events.

So instead of

time: 2.000 status: [FIRST_ENTERED, FIRST_HOVER]
time: 2.008 status: [HOVER]
time: 2.015 status: [FIRST_PRESS]
time: 2.023 status: [PRESS]
time: 2.030 status: [PRESS]
time: 2.038 status: [PRESS]
time: 2.045 status: [FIRST_HOVER]
time: 2.053 status: [HOVER]
time: 2.060 status: [HOVER]
we have

time: 2.000 status: [HOVER, FIRST_ENTERED, FIRST_HOVER]
time: 2.008 status: [HOVER]
time: 2.015 status: [PRESS, FIRST_PRESS]
time: 2.023 status: [PRESS]
time: 2.030 status: [PRESS]
time: 2.038 status: [PRESS]
time: 2.045 status: [HOVER, FIRST_HOVER]
time: 2.053 status: [HOVER]
time: 2.060 status: [HOVER]

Just simplifies things a bit if you want to, for example, just filter out all non-inking sequences.

**Comment by g-no** [comment]
Ok, good.

**Comment by isolver** [comment]
Done. You will get it in Dec 21st, 2015 build.
