### ISSUE TITLE
XML (handspy) files won't now open

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#113]
Like it says. No crash or error, just no data appears.

**Comment by isolver** [comment]
update: tested with latest code and data is now loading, but sample times are being rounded to the second, so a bunch of samples have the same time. This is a really weird bug.....

**Comment by Mark-Torrance** [comment]
Naively: int instead of float, possibly as a result of using old-style division?

**Comment by isolver** [comment]
I've gone through all that, even to the point of explicitly casting
everything to floats, so while I thought that would be the issue too, it
does not seem to be.

**Comment by isolver** [comment]
fixed. 

Caused by me changing markwrite numpy sample table time field to float32 to try and save 4 bytes per sample (it was float64). ooops. 

Put it back to using float64 so very large timestamps, like those in the xml files, are handled correctly.
