### ISSUE TITLE
Add data file loading progress dialog

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#114]
Now, loading a pen data file will stall markwrite while it is being loaded, leaving user wondering what is going on for a few (or more) seconds. Add a progress dialog that reports % of file loaded & processed. The dialog should stay visible until the plot views become populated with the loaded data.

**Comment by Mark-Torrance** [comment]
I noticed this too - good plan.

**Comment by isolver** [comment]
fixed
