### ISSUE TITLE
Option to turn off stroke marker display

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#117]
In poor quality (eye and pen) data where there are lots of skipped samples (i.e. inter sample interval flips between 4 and 8 ms) stroke detection isn't possible. We need to have the option of turning off stroke marking in the time line. Setting stroke boundary point size to zero removes stroke boundary markers in just the spatial and selected views.

**Comment by isolver** [comment]
Setting it to 0 should turn it off in all views, so this is a bug and I'll
fix it.

**Comment by isolver** [comment]
fixed & committed to github
