### ISSUE TITLE
Perform segment autotrim prior to showing "Create Segment" Dialog 

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#12]
From Mark: 

> the auto-trim thing, where the selection automatically fits tightly around a word, is very useful, but 
> needs (a) act before a segment is labelled – so the autotrim happens as the labelling dialogue 
> appears (so you can reject the segment that you’re then being offered without having to type a lable),

My input is that I guess if the user cancels the segment creation, then the selection should be 'untrimmed' so that it goes back to how it was before starting the create segment action. @Mark-Torrance, do you agree?

**Comment by Mark-Torrance** [comment]
Yes, that makes sense.

**Comment by isolver** [comment]
Implemented.
