### ISSUE TITLE
Have a happy Christmas and excellent New Year!

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#120]
:evergreen_tree: :star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree: :star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree:

It's been great working with you, and I think we're going to end up with something that we can be very proud of.

I'm now going to try and forget all about this until next year!

:evergreen_tree: :star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree: :star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree::star::evergreen_tree:

**Comment by isolver** [comment]
> It's been great working with you, and I think we're going to end up 
> with something that we can be very proud of.

Same to both @g-no and @Mark-Torrance . Agreed about the app too.

> I'm now going to try and forget all about this until next year!

Me too.  I'm closing this issue to make it official. ;)
