### ISSUE TITLE
Keep up the great work! This project needs financing and more support!

### ISSUE THREAD

**Issue by timofonic** [isolver/OpenHandWrite#121]
Hello.

I was looking at FOSS alternatives to Google Handwriting and MyScript technologies, they are extremely advanced in comparison to the FOSS ones. The same applies to OCR technology, despite it has lots of shortcomings.

I hope your project gets more attention and developers, it really deserves it. There aren't proper FOSS HWR engines out there. This is an underrated field, it's very useful for education and accesibility but also as a user interface for tactile devices too.

Most software runs in the cloud, they hide their secret sauce. I know this is very hard and their software is probably massively trained to work the best way, something  FOSS project can't have without proper resources.

Kind regards.

**Comment by isolver** [comment]
@Mark-Torrance & @g-no, did you see this posting?

**Comment by Mark-Torrance** [comment]
I did. It would be encouraging if the poster hadn't understood the project as developing a handwriting recognition tool, but thanks anyway @timofonic :)

**Comment by isolver** [comment]
;)

**Comment by timofonic** [comment]
I'm sorry. I feel like a total fool right now.


What's the goal? Is it for experimental or therapy purposes? A short description would be really appreciated to avoid other fools get confused :D

**Comment by Mark-Torrance** [comment]
Don't feel a fool @timofonic! I've had a look at the home page and the first page of the Wiki (https://github.com/isolver/OpenHandWrite/wiki/Introduction) and both could be read as automatic handwriting-to-text. Which in fact would be very cool in this context, by unlikely to ever be accurate enough. These are tools for psycholinguists specifically interested in understanding cognitive processes underlying written language production.
