### ISSUE TITLE
Normalizing sample time stamps is problematic for time related condition variables (hdf5 only)

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#125]
Right now in markwrite, samples are loaded from the data file, and are all normalized to 0.0 by subtracting a constant offset from all sample times. The offset == the time of the first sample. If trial start and end time condition variables were identified when the file was loaded, these two condition variables are also normalized using the offset.

The issue is that is any other condition variables recorded to the hdf5 file represent an experiment event time (like stim onset, manual RT, etc), these times are not normalized, making comparison to sample times invalid. There is currently no way for markwrite to know that these other condition variables also need to be normalized to the markwrite projects time offset.

Obvious solution would be to not normalize sample times in markwrite. Not sure how important the time normalization step is. If it is important, then we need to determine how to handle this issue. Possibilities:  

1) do nothing code wise; users would need to normalize other condition variables that are being used for comparison with pen sample times. The time offset used to do sample normalization is saved as an attribute of the markwrite project class, so is accessible during report generation.
2) as part of the hdf5 file loading process, add a dialog that lets a user select 0 - N condition variable names. The values for these variables would then be normalized when the file is loaded.
3) add a setting to the app settings dialog that lets users specify a string that is used to identify any condition variables that should be have their values normalized; default for string key could be 'TIME' or something. If the string token is found anywhere in the label of a condition variable, all values for that variable are considered to represent experiment times, and are normalized along with pen sample times.
4) ????

**Comment by Mark-Torrance** [comment]
The original reason for normalising I thought was largely to reduce file size? This still seems a good goal. It also makes raw times more readable. Not sure if that's important.

I suggest 3, though maybe permit a list of strings, so that if a user has forgotten to give a single unique tag to all time variable names they can still identify them

Could we then normalise to the earlies time stamp, rather that the first sample time? Times are very likely to be recorded prior to the first sample, and it would be nice (or essential?) to avoid negative normalised times.

**Comment by isolver** [comment]
There is no impact on memory or file size given the huge initial time
stamps we need to support for the xml file examples. I think it was mainly
a readability / usability concern.

> Could we then normalise to the earlies time stamp, rather that the first
> sample time? Times are very
> likely to be recorded prior to the first sample, and it would be nice (or
> essential?) to avoid negative
> normalised times.

Good point, so this is another TODO:
- if trial segments are being created, sample times will be normalized
  using the trial start time variable for the given sample. Otherwise times
  will be normalized using current code.

**Comment by isolver** [comment]
Correction to:

> - if trial segments are being created, sample times will be normalized
>   using the trial start time variable for the given sample

Should have read:
- if trial segments are being created, sample times will be normalized
  using the first trial's start time.

**Comment by isolver** [comment]
Implemented. The condition variable columns that should be treated as holding experiment times, and therefore should have their values normalized, are specified using the app setting "Experiment Time Condition Variables Filter". This setting can contain a string that is used to select cond. var. column names, logic used is same as "Start Time Options Filter" and "End Time Options Filter" app settings. 

If cond vars selected by  "Start Time Options Filter" and "End Time Options Filter" are found in "Experiment Time Condition Variables Filter" results, they are ignored, as they already have had their values normalized.

Below is description of how filter str can be used for all three of these app settings.

```
def getFilteredStringList(slist, filterstr):
    """
    Given a list of strings slist, find those that match filterstr.
    filterstr has two special characters which can not be
    used in condition variable names themselves:
    a) ',': use to indicate more than one possible filter string
    b) '*': Each filter string can have <= 1 '*' char, and is
            used as you would when searching for files in your OS.
    filterstr Examples:
    a) "DV_*_START":
       Returns any elements of slist that start with 'DV_'
       and end with '_START'.
    b) "*_TIME":
       Returns any elements of slist that end with '_TIME'.
    c) "RT_*":
       Returns any elements of slist that start with 'RT_'.
    d) "*_TIME, RT_*":
       Returns any elements of slist that end with '_TIME'
       OR start with 'RT_.
    """
```

**Comment by isolver** [comment]
Note: Updated app setting label to: "Exp. Time Condition Variables"
