### ISSUE TITLE
RawSampleDataReport finds >1 stroke for some samples

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#126]
The updated RawSampleDataReport outputs a column giving the stroke ID that the current sample falls within, if any. I believe it is correct to think that a sample should at most belong to 1 detected pen stroke. If this is incorrect, let me know.

The issue is that for the first and/or last sample of a stroke, sometimes two strokes are currently identified as containing that sample. This is because the current code that selects the samples that fall within a stroke includes the  stroke boundary start sample and the stroke boundary end sample. Therefore, the last sample in stroke S is also selected as the first sample of stroke S+1.

How do you want this fixed? Should the samples selected for a given stroke include the stroke boundary start sample and go until:
- 1 sample prior to the stroke boundary end sample if the end sample is also the next stroke boundary's start sample
- existing logic if the end sample is not the first sample in the next stroke?

**Comment by Mark-Torrance** [comment]
Or, simpler and permits a single definition of stroke: Selected samples always end on the sample prior to the stroke boundary.

Actually, I'm not sure that I understand this:

> existing logic if the end sample is not the first sample in the next stroke?

Given that all we are doing is identifying stroke boundaries, doesn't this mean that all samples are "in" a stroke. Ah, except for the very last sample in a trial. Was that what you were thinking about?

**Comment by isolver** [comment]
On Tue, Jan 12, 2016 at 5:23 AM, Mark Torrance notifications@github.com
wrote:

> Given that all we are doing is identifying stroke boundaries, doesn't this
> mean that all samples are "in" a stroke. Ah, except for the very last
> sample in a trial. Was that what you were thinking about?

Last stroke sample / boundary point in each sample series or each pressed
run will not have a next stroke that uses the same sample for its starting
boundary point. Whether it is at the series or run level depends on the app
setting that defines whether strokes are created regardless of pressed
state, or for pressed samples only.

**Comment by Mark-Torrance** [comment]
Ah yes. Of course. I still think we should keep things simple and always have all strokes running from stroke boundary to one sample before stroke boundary, regardless of what comes next.

**Comment by isolver** [comment]
@g-no : do you have any opinion / preference for this? If not I will implement as Mark has suggested. Thank you.

**Comment by isolver** [comment]
fixed. Stoke is selected as stroke boundary start sample -> stroke boundary end sample -1. This rule is used for all strokes, even if stroke is last one in series or run.
