### ISSUE TITLE
Various, from 14.01.16. build

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#128]
To be either made into separate issues or dropped
- [x] As far as I can tell Increase / decrease selected End Time / Start Time currently mapped to ctrl/alt PgUp/PgDown (and with their own icons) are exactly the same as the move-by-run actions currently mapped to ctrl(+shift)+Left/Right (and with their own icons. The Increase / decrease selected End Time / Start Time actions, which are from the previous version, can go? See crossed through icons in image below.
- [x] I've created a new set of action icons. Same shape as before but a bit sharper and all with transparent background. For strokes I've just removed the bottom line, on the grounds that this is the lowest level of move, and given the point above, we don't now need these icons for anything else. I've changed the icons for the "jump whole selection forward" so that they don't look like "undo" and "redo". Not sure that the new one is self-explanatory, but it will probably do? Icons here: https://dl.dropboxusercontent.com/u/8908850/new_selection_icons.zip  I've tested them and they look ok to me. 
  ![new_selection_icons](https://cloud.githubusercontent.com/assets/3226576/12374328/2118e9d0-bc90-11e5-971d-6fce8bd14b7c.PNG)
- [x] Project saving and opening is working fine for me, but the progress dialogue doesn't appear from the start of opening. So there is a scary wait when nothing happen, then the project appears.
- [x] Not an issue. Just want to say how well the stroke detection / selection / display is working. It was well worth putting time and effort into this @g-no and @isolver . I'm very impressed.
- [x] If it's easy to do it would be nice to add the currently-set keyboard shortcuts to the hover-over text associated with the icons. This would substantially speed up learning the quick-keys, I think.
- [x] It is currently possible to move the selection to before and after the currently-selected trial. This is confusing: Points start appearing the spatial view from other trials, and the selection moves off the timeline. Can we prevent this happening?
- [x] I can't get the batch report .bat file to run. Running from the script within Spyder, but with I think the right working directory. Sorry, Sol, should have checked before you went away. I get this...

```
runfile('C:/openWrite/OpenHandWrite/markwrite/batchreportgen.py', wdir='C:/openWrite/OpenHandWrite/markwrite')
Traceback (most recent call last):

  File "<ipython-input-1-c7fcfeb026ed>", line 1, in <module>
    runfile('C:/openWrite/OpenHandWrite/markwrite/batchreportgen.py', wdir='C:/openWrite/OpenHandWrite/markwrite')

  File "C:\openWrite\OpenHandWrite\WinPython\python-2.7.10.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "C:\openWrite\OpenHandWrite\WinPython\python-2.7.10.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/openWrite/OpenHandWrite/markwrite/batchreportgen.py", line 8, in <module>
    import markwrite

  File "markwrite\__init__.py", line 28, in <module>
    usersettings = readPickle(appdirs.user_config_dir,u'usersettings.pkl')

  File "markwrite\file_io.py", line 303, in readPickle
    return cPickle.load(f)

SystemError: ('unable to find to find type: QString', <built-in function _unpickle_type>, ('PyQt4.QtCore', 'QString', (u'Alt+PgUp',)))
```

**Comment by isolver** [comment]
I'm going to split these into individual issues so a separate discussion thread can be had for each. I'll tick off each one here as I add the new issues, and close this issue when all of them have been split out.

**Comment by isolver** [comment]
created as separate issues #130 to #136
