### ISSUE TITLE
Support multiple segment autotrim modes

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#13]
Support two to three different algorithms for auto trimming a newly created segment. 
- [x] Inclusive with trim to samples with pressure > 0 (default)
- [x] Inclusive with trim to sample (what is currently implemented)

Maybe at some point:
- [ ] Exclusive without trim (add only if we find after use that it’s needed but keep on wishlist as a reminder).

Note on GUI interface implementation for this:
- [x] User should be able to select which autotrim mode to use from the (Yet to be implemented) "Project Settings" dialog.

**Comment by isolver** [comment]
@Mark-Torrance : For the  trimming option of:

> Inclusive with trim to samples with pressure > 0 (default)

Should this mask out all points in the segment that have pressure == 0, or just  any points at the start and end of the array but not in the middle?

**Comment by Mark-Torrance** [comment]
Just at start and end. Also, this should become the default.

**Comment by isolver** [comment]
Ok and yup. Thanks

**Comment by isolver** [comment]
Done:
-  Inclusive with trim to samples with pressure > 0 (default) added.
- Setting can be changed from the Project Settings Dialog (first setting in dialog).

I'm closing this issue, even though the maybe someday:

Exclusive without trim (add only if we find after use that it’s needed but keep on wishlist as a reminder).

feature has not been added. If it should be tracked for future release we should create a new issue just for it.

**Comment by isolver** [comment]
BTW, This needs more testing I would think. I did enough testing to believe that it is working as expected when on and off, but some extra verification by another set of eyes would be good for this.
