### ISSUE TITLE
project loading progress bar

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#130]
> Project saving and opening is working fine for me, but the progress dialogue doesn't appear 
> from the start of opening. So there is a scary wait when nothing happen, then the project appears.

**Comment by isolver** [comment]
@Mark-Torrance : do you mean it does not appear at all, or that it takes a while to appear just before the project itself opens?

**Comment by Mark-Torrance** [comment]
There's a long time before it appears, then it appears very very briefly (I think - too quick to be sure that's what it is), then the project opens.

**Comment by isolver** [comment]
Since the dialog appears when it should on my PC I have made changes based on guesses as to what could be delaying the dialogs display.
1. reduced dialog display delay from 250 msec to 100 msec.
2. Update the dialog progress bar right after the file importer object created, but before the data is actually read.

Please let me know if you still have issues with this once you get the updated code.

**Comment by Mark-Torrance** [comment]
Still present on my computer. Note that this is loading a saved project, not a raw data file. I get a lag (quite a long one for big projects) and then the progress box (I'm guessing) appears for no time, then the project immediately opens.

**Comment by isolver** [comment]
On Thu, Jan 28, 2016 at 8:45 AM, Mark Torrance notifications@github.com
wrote:

> I get a lag (quite a long one for big projects) and then the progress box
> (I'm guessing) appears for no time, then the project immediately opens.

OK, if this is for saved projects only, not for creating a new project by
loading source data file file, then I need to look at different code. Sorry
about that.

**Comment by Mark-Torrance** [comment]
Issue remains in 1st Feb distro.

**Comment by isolver** [comment]
OK, made another attempt. Will be in build 0.2.2.6

The progress dialog may not move for a period of time when opening a saved MW project, but it should appear right after you select the file and hit the Open button.

Please let me know if it works on your PC.

**Comment by isolver** [comment]
@Mark-Torrance : does this at least show up for your now when openning a saved markwrite project file? OK to close this issue?

**Comment by Mark-Torrance** [comment]
Sorry, meant to say: I checked (and  I’ve checked again with 2.2.8) and this works fine now.

**Comment by isolver** [comment]
Great. Closing.
