### ISSUE TITLE
stroke parsing

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#131]
> Mark wrote: Not an issue. Just want to say how well the stroke detection / selection / display is working.
> It was well worth putting time and effort into this @g-no and @isolver . I'm very impressed.

Thanks Mark! I would like to know if @g-no has a similar opinion on this or not. ;) Is it at a state that you are fine with for now, or are there any major issues that need to be addressed?

**Comment by g-no** [comment]
Yes, basically I'm happy with the stroke detection. Further improvements could be done, but will need more testing (and reading). I'll look into this in the future.
Two possible imrpvements for now (will open new issues for this):
1. Changing the settings for stroke detection needs reloading the file. It would be cool to let them take effect immediately (seeing the effect while having the settings dialogue open, or at least without reloading the file).
2. An alternative and very basic approach would be to set stroke boundaries at every local Y-minimum and maximum (maybe using an adjustable "window size").

**Comment by g-no** [comment]
New issues #178 and #179 are open. I'll close this one.
