### ISSUE TITLE
include shortcut key to action tool tips

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#132]
> Mark wrote: If it's easy to do it would be nice to add the currently-set keyboard shortcuts
> to the hover-over text associated with the icons. This would substantially speed
> up learning the quick-keys, I think.

I had the same thought while doing this and spent a bit of time looking into an efficient way of implementing this, which basically means having a given QActions tooltip text updated when the 'associated' shortcut preference is changed. Did not come up with anything easy to implement then. Will have another quick look / think.

**Comment by isolver** [comment]
A quick way to do this would be via brute force: if any keyboard short setting is changed, update the text for **all** action tips.

**Comment by Mark-Torrance** [comment]
Brute force sounds fine. This is a rare user action and not at a time when a bit of a lag matters. I'm thinking in terms of people looking quickly at the software to decide it it's for them, and for introducing it quickly in a training session. I think think like this could make a big difference in that context.

**Comment by isolver** [comment]
Implemented. 

@Mark-Torrance : Note that it appears in the status tip text (at the bottom of the markwrite app window), not in the text that is displayed if you mouse over and hover on a toolbar icon. Is this OK?
