### ISSUE TITLE
update action icons

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#136]
From Mark:
 I've created a new set of action icons. Same shape as before but a bit sharper and all with transparent background. For strokes I've just removed the bottom line, on the grounds that this is the lowest level of move, and given the point above, we don't now need these icons for anything else. I've changed the icons for the "jump whole selection forward" so that they don't look like "undo" and "redo". Not sure that the new one is self-explanatory, but it will probably do? Icons here: https://dl.dropboxusercontent.com/u/8908850/new_selection_icons.zip  I've tested them and they look ok to me. 
![new_selection_icons](https://cloud.githubusercontent.com/assets/3226576/12374328/2118e9d0-bc90-11e5-971d-6fce8bd14b7c.PNG)

**Comment by isolver** [comment]
Done.

@Mark-Torrance,  thanks for updating the icon images and making them transparent. What program did you use to save / export the png images in? It seems to also fix the warning that is printed when the app is started using the previous icons:

```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
```

so it would be good to resave the other icons using that program as well and get rid of all the warnings.

**Comment by Mark-Torrance** [comment]
I imported nice sharp edged icons into http://pixel.tools/ and where necessary removed them white background, then did lots of cut and pasting to create new shapes, then exported to irfan view with a green background, then saved as png with background -> transparent and no compression. I'll have a play and see if any combination of those work for the other icons.

Mark

**Comment by Mark-Torrance** [comment]
Done. Tested and they work (with no error).
[icons.zip](https://github.com/isolver/OpenHandWrite/files/101207/icons.zip)
Batch processed existing icons in Irfanview with 
- save transparency as alpha channel (it then prompts you to click on the transparency colour for each image)
- zero compression / binary encoding
- use PNGOUT plugin with the RGB option set (not sure if that was needed)

**Comment by Mark-Torrance** [comment]
Woops missed one:

![edit 32](https://cloud.githubusercontent.com/assets/3226576/12518770/67ffc412-c132-11e5-9a79-a194aa76a669.png)

**Comment by isolver** [comment]
Yahoo, thank you. ;)

**Comment by isolver** [comment]
This one seems to have a black background instead of being transparent.
Maybe just from copying it to github URL? Maybe try resending in a zip file?

Thanks again,

Sol

**Comment by isolver** [comment]
Disregard my last comment about the edit&32.png; it is black when copied from the email notification from github, but is fine if I download via the github issue webpage.

So all is good! Closing issue...
