### ISSUE TITLE
update txyp file importer

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#137]
See issue #112 for details. Basically, need txyp importer class to remove any samples that are isolated 0 pressure rows from the sample array provided to markwrite.

**Comment by Mark-Torrance** [comment]
Copying from #112 

> > Just seems like a real shame to totally loose the distinction between sample series and the sample runs within each series. It seems like useful information to me at least. ;)
> 
> MT: I think the bottom line is that in these data we don't know anything about series. So we just need to acknowledge that. I'm suggesting that we make series logically equal to run, which will mean that all segment selections work in a non-scary way. Alternatively we could just have a single FIRST_ENTER at the start of the session, which would be more accurate but would mean that if you accidentally hit a series select action not-nice things would happen. For creating reports, you'd just have to remember that anything to do with series was not meaningful.

Just to be really clear. The above refers to txyp and xml files, not to hdf5 files where of course we want to maintain the series / run distinction (in selection actions and in reports)

**Comment by isolver** [comment]
- So the single 0 pressure 'fake' samples found in the txyp file format will generate FIRST_PRESSED status state, which will be used by markwrite to parse sample Runs. 
- txyp will not support Series level parsing.

**Comment by isolver** [comment]
Implemented.

Import class:
- skips first 2 rows of file
- skips rows with pressure == 0, sets last_sample = None
- rows where pressure > 0 are included as samples. 
  - if last_sample is None, current sample status = ['FIRST_PRESS','PRESSED'], otherwise status = ['PRESSED']. 
  - set last_sample = current sample.
- importer never sets status state to include HOVER, FIRST_HOVER, or FIRST_ENTER
- Series level parsing not supported.
