### ISSUE TITLE
update xml file importer

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#138]
Use the 'strokes' element to group samples into pressed runs.

Should ISI be used to do the top level series splitting though, or should series == run for xml files?

**Comment by Mark-Torrance** [comment]
This...

> series == run for xml files?

..I think.

**Comment by isolver** [comment]
So strokes will generate FIRST_PRESS status state, which will be used by markwrite to parse sample Runs. xml will not support Series level parsing.

**Comment by isolver** [comment]
Note that in current implementation, importer class set first sample of each strokes pressure to 0. 
I guess this was how we were telling markwrite when each pressed run finished. This will no longer occur in the new implementation.

**Comment by isolver** [comment]
Implemented.

Import class:
- uses <strokes> </strokes> element to parse sample Runs.
- all sample pressure values is set to 1.
- for each <strokes> element: 
  - first sample of strokes element has status = ['FIRST_PRESS','PRESSED']
  - all remaining samples in a strokes has status = ['PRESSED']. 
- importer never sets status state to include HOVER, FIRST_HOVER, or FIRST_ENTER
- Series level parsing not supported.

Note regarding markwrite stroke detection:

Some of the xml test files have strokes with only 1 sample in them. For example, 66.xml:

```
<strokes start="40527839165" end="40527839165">
<stroke Time="40527848901" X="1419" Y="2577"/>
</strokes>
```

When the markwrite setting "Use Pressed Sample Runs Only" is True, a strokes (== Sample Run) with only 1 sample is not parsed by the markwrite pen stroke detector. The sample will therefore have no stroke id associated with it.
