### ISSUE TITLE
move to next unit end actions not working

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#140]
- [x] None of the "move selection to end of next ??" actions are working, either from keyboard or clicking action icons. All other actions seem to be working perfectly. This is specific to hdf5 files. txyp seems fine (except move selection to next stroke sometimes doesn't work, when it should. Though the strokes aren't detected well in those files anyway for crazy ISI reasons).

**Comment by isolver** [comment]
I do see that "Move Selection End to Next Stroke End" sometimes stops working, but the 'Pressed Run' and 'Series' compliments seem to always work for me, assuming there is a next unit end to move to of course.

What input file are you testing with? I have tried both hdf5 and the 90.txyp.

Thanks!

**Comment by Mark-Torrance** [comment]
I was testing with this exp_template_data.hdf5. Checked again and still there. This isn't just "sometimes doesn't work". No action at all, in situations where it would definitely be a legal move.

The other problem was is with 90.txyp and 1.tab.txyp - do you see that one?

**Comment by Mark-Torrance** [comment]
See edited first check-item above.

**Comment by isolver** [comment]
Fixed the move to next to end issue. Will email you update.

**Comment by isolver** [comment]
Re second issue, see what you mean, will need to look at that tomorrow am. Will create separate bug for it since it is a separate issue.

**Comment by Mark-Torrance** [comment]
Update working fine for me. Good.
