### ISSUE TITLE
Change Report toolbar button functionality

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#143]
Bumping up the actual issue to be addressed:

> The best functionality would be for that button to bring up an Export dialogue and you choose which report. Fine as it is now, though. Simple users can either just click for a default segment reports. Super-users are not going to be phased by having to find their super-reports via the menu.

So just have one toolbar button for "export Report" and then a popup with a single select list of the items in the File->Export menu?

---

Below is not relevant for updated issue title.

~~Currently we have PenSample and SegmentLevel reports defined, and as I understood it, I can add more of these report classes. If I want to create these reports from within the GUI, what do I do. The save button currently just saves the Segment Level resport.~~

Ah, found it. 
- [ ] Default directory for saving should be the same folder as the input data? This is where projects are currently saved, but not reports. Minor, but it's messy having the openHW root as the default, and different defaults for project and report.
- [ ] So, if I create a new ReportExporter instance for a new custom report, how do I run that from within the GUI? Is doing so actually possible? This isn't essential, but it would be good.
- [ ] Do we need to remove the segment save button (as it is duplicated on the Export menu)? It seems a bit odd to have a button specifically for one report.

**Comment by isolver** [comment]
> Default directory for saving should be the same folder as the input data? This is where projects are currently saved, but not reports. Minor, but it's messy having the openHW root as the default, and different defaults for project and report.

Agree. High priority?

> So, if I create a new ReportExporter instance for a new custom report, how do I run that from within the GUI? Is doing so actually possible? This isn't essential, but it would be good.

Yes it is possible.
To create a new ReportExporter and have it available in the GUI (via File->Export->....) you need to add the ReportExporter subclass you are defining to the markwrite/customreports.py file. When markwrite starts up, it creates a menu item for each custom report defined in that file. This is where the Raw Sample Report in the Export menu is coming from.

> Do we need to remove the segment save button (as it is duplicated on the Export menu)? It seems a bit odd to have a button specifically for one report.

The idea was that the 'built in' report types would have toolbar icons; so 2 reports have toolbar buttons: the sample and segment reports. 

Ideally, the ReportExporter class could have an icon_path class attribute that could give the relative path of an icon to use for the report. If set for a custom report, then a toolbar button could be created for that custom report as well. Future functionality?

**Comment by Mark-Torrance** [comment]
> > Default directory for saving should be the same folder as the input data? This is where projects are currently saved, but not reports. Minor, but it's messy having the openHW root as the default, and different defaults for project and report.
> 
> Agree. High priority?

Yes, I think so. Unless its time consuming to do. Little things like this make a difference, I think.

> > So, if I create a new ReportExporter instance for a new custom report, how do I run that from within the GUI? Is doing so actually possible? This isn't essential, but it would be good.
> 
> Yes it is possible.
> To create a new ReportExporter and have it available in the GUI (via File->Export->....) you need to add the ReportExporter subclass you are defining to the markwrite/customreports.py file. When markwrite starts up, it creates a menu item for each custom report defined in that file. This is where the Raw Sample Report in the Export menu is coming from.

Sorry, I remember this now. And you've got a way of automatically extracting menu item label from the customreport name. Good. I'll move this to the (draft) wiki.

> > Do we need to remove the segment save button (as it is duplicated on the Export menu)? It seems a bit odd to have a button specifically for one report.
> 
> The idea was that the 'built in' report types would have toolbar icons; so 2 reports have toolbar buttons: the sample and segment reports.

Ah, sorry. For some reason I that the sample button has been reused for projects, but checked and no.

> Ideally, the ReportExporter class could have an icon_path class attribute that could give the relative path of an icon to use for the report. If set for a custom report, then a toolbar button could be created for that custom report as well. Future functionality?

The best functionality would be for that button to bring up an Export dialogue and you choose which report. Fine as it is now, though. Simple users can either just click for a default segment reports. Super-users are not going to be phased by having to find their super-reports via the menu.

**Comment by isolver** [comment]
> The best functionality would be for that button to bring up an Export dialogue and you choose which report. Fine as it is now, though. Simple users can either just click for a default segment reports. Super-users are not going to be phased by having to find their super-reports via the menu.

So just have one toolbar button for "export Report" and then a popup with a single select list of the items in the File->Export menu? This is a good idea and would take 15 minutes to do. Should I?

**Comment by Mark-Torrance** [comment]
Yes, I think so? If it's quick, then it would be worth it.

**Comment by isolver** [comment]
fixed.
