### ISSUE TITLE
Double clicking on segment label in segment tree shouldn't collapse segment

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#144]
When you double click on a segment in the segment tree, to zoom in on that segment, it also collapses that branch. This is a minor annoyance. We talked about it before, I think, and it's a pyqt default? If there is any way of switching this behaviour off, that would be good.

**Comment by isolver** [comment]
> it's a pyqt default?
> Yes. 

I agree it would be better if it did not collapse the segments subtree.

**Comment by isolver** [comment]
Took 10 minutes to research and implement. So fixed.

**Comment by Mark-Torrance** [comment]
Excellent.
