### ISSUE TITLE
A place for wiki images

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#145]
This is just a place to put (and possibly admire) images for the wiki. This uploads the image and creates an URL that can be used in the wiki (you can't just copy image files into wiki pages).

![mw_screencap_velocity acc](https://cloud.githubusercontent.com/assets/3226576/12646474/443f3a18-c5c8-11e5-9299-e7b424a3afa9.png)

**Comment by isolver** [comment]
We could also add a folder to the github project that is used to hold wiki images. They could be linked to from there there. It looks like the github browser interface now allows collaborators to add files to a project by drag and dropping them right into the github repo folder that is currently open in the web browser being used:

![githubuploadp](https://cloud.githubusercontent.com/assets/1795082/13584550/1be08d84-e485-11e5-9d42-0c9811748a61.png)

**Comment by g-no** [comment]
When using Firefox I'm getting the following message: "Something went really wrong, and we can’t process that file. " Using Edge (the new MS browser) it worked. I can't create a folder though. Maybe a folder called "img" in the "docs" folder would be a good place.

Guido

**Comment by Mark-Torrance** [comment]
Just adding them to this issue works pretty well I think (though I agree it’s a bit odd) It also means you can annotate them.

Mark

**Comment by isolver** [comment]
On Wed, Mar 9, 2016 at 9:42 AM, g-no notifications@github.com wrote:

> Maybe a folder called "img" in the "docs" folder would be a good place.

Added suggested folder to github project.
