### ISSUE TITLE
Changing the point size on the velocity graph is buggy

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#146]
Make a change in settings to the point size (possibly also colour), but this change does not appear in the display straight away. It does after several tries (not sure what I changed between tries). Accelaration, x, y, and all other setting are fine.

**Comment by isolver** [comment]
Humm, I can not reproduce this one. I have tried several different files. The point size in the velocity trace always seems to change after I press the OK button in the settings dialog.

Could it be that you were pressing the top right 'x' to close the settings window and not the 'OK' button?

**Comment by Mark-Torrance** [comment]
> Could it be that you were pressing the top right 'x' to close the settings window and not the 'OK' button?

I wouldn't put it past me, but no, pretty sure not. As I say, I can change other settings fine, and I've found this more than once, with different OHW projects.

Leave it, though. It's really not important.

**Comment by isolver** [comment]
@g-no reported further issues:
- [x] Point size for Horizontal Pen Position Trace doesn't have an effect
- [x] Point size for Velocity Trace doesn't have an effect
- [x] Point size for Accelleration Position Trace doesn't have an effect

**Comment by isolver** [comment]
Fixed
