### ISSUE TITLE
create standalone exe for MarkWrite GUI app

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#151]
As was done for the phase 1 version of the app. This will require updating the OpenHandWrite\markwrite\freezeApp.py file and spend X amount of time fixing stupid issues related to cx_Freeze that are guarenteed to come up when first trying to create the exe.

**Comment by Mark-Torrance** [comment]
Thanks Sol. I was worrying a bit about this. 

Is there anything we can do to strip out the bits of Winpython that are not MarkWrite or GetWrite dependencies now, without it taking ages? I've been having a quick look at this, for example, http://furius.ca/snakefood/

I can imagine people being a bit wary of 1.8GB, particularly if they are just using MarkWrite, and will not be doing any developing.

**Comment by isolver** [comment]
I thought I had replied to this last night, but I guess I did not hit submit.

Anyhow, spent 1.5 hours hacking on getting a MarkWrite exe this am. I have something that I think works (runs on my PC at least). It is a 32 bit app BTW.
1. I will send a link to a MarkWrite 0.2.2.1.7z file. 
2. Once extracted, you will have a MarkWrite folder. 
3. Run MarkWrite/MarkWrite.exe app. 

Please let me know if this works.

This is a hack job at this point though:
    1) Using cx_freeze for something that uses psychopy (which means psychopy.iohub too) causes major issues / errors. I have hacked a version of psychopy that gets around the errors. Really psychopy itself needs to be updated with more proper / permanent solutions.
    2) The script that creates the MarkWrite exe must be run using the copy of WinPython that I have on my harddrive: XXXXXX/WinPython-32bit-2.7.6.0/. I will make a zip of this folder and upload it to google drive so it does not get changed.

When there is time, a non hack process for doing this can be done. :)

**Comment by Mark-Torrance** [comment]
Tested. Sorry for the delay. Not working I'm afraid:

![capture](https://cloud.githubusercontent.com/assets/3226576/12699215/3f3e1dce-c7ab-11e5-80b4-0e65f0f9bb1f.PNG)

**Comment by isolver** [comment]
bummer. wish the error said what dll was not found. ;(

**Comment by isolver** [comment]
Notes:
1. The stand alone exe approach is likely going to cause issues for someone who writes a custom report and tries to use any python module or package that was not included with the MarkWrite exe build.
2. All these issues in creating the MarkWrite.exe come from needing to import psychopy, which needs scipy etc. The only need for importing psychopy is so that psychopy.iohub.datastore module can be used to read the iohub hdf5 files. This is a bit crazy since there is one file in all of psychopy.iohub that is needed to read the hdf5 files. Point: it maybe easier / faster, to break out that one file and have a copy in the markwrite source. Then psychopy would not need to be imported by markwrite at all, and the hdf5 files could be read using the functions that work with pytables directly.

**Comment by Mark-Torrance** [comment]
Point 2 makes sense to me. The standalone is much more important for MarkWrite than it is for GetWrite, at least initially as we try to get people to use it. I couldn't work out why this required the whole of PsychoPy and its dependencies.

**Comment by isolver** [comment]
Agreed. Sorry about all these setup issues Mark. They are important to
correct so end users do not have issues when first starting to try
markwrite. First impressions matter here.

**Comment by Mark-Torrance** [comment]
I'm not too worried about money. I need to check budget but I'm fine for 2750 GBP. So please continue to charge this. It just might eat a bit into the "future troubleshooting" budget (but even that's unlikely).

My impression is that we are very close, and I am really pleased with what we have.

**Comment by Mark-Torrance** [comment]
> The stand alone exe approach is likely going to cause issues for someone who writes a custom report and tries to use any python module or package that was not included with the MarkWrite exe build.

Sorry, didn't comment on this before. I'm relaxed about this. Anyone wanting to create a custom report is going to also be happy using the full distribution. In the short to medium term I think the only person likely to be doing this is me. Certainly not casual users who are just trying it out.

**Comment by isolver** [comment]
@Mark-Torrance : I removed some comments from above realizing they were better not on a public site. In reply to them though, thanks very much for your understanding and support.

I have made another stab at the stand alone MarkWrite exe stuff. I will send you a link shortly. I have hopes this one will work for you, as I copied it to Amy's PC and tested it there and it seems to work fine.

Plus's:
- the cx_freeze script uses the OpenHandWrite/WinPython distro. So no need to worry about it only working when used in a python distro != what OpenHandWrite provides.
- no changes to psychopy are needed, as psychopy / iohub are not used by MarkWrite anymore.

Con's:
- The download file is 60 MB (compressed into 7z self extracting archive). Uncompressed folder size is ~458 MB. This is about 2x the previous size, but was necessary so that all the DLLs needed were included. MarkWrite requires scipy (pyqtgraph dependency), so that is a lot of space in itself.

**Comment by isolver** [comment]
Updated the numexpr package winpython is using, as someone else reported getting the same error as you last reported when trying to run a cx_freeze app with the older version.

@Mark-Torrance Can you please get the MarkWrite_v0.2.2.6.exe archive from the SHARE folder, extract it, and try running this one? If you still have issues, please try putting the MarkWrite_v0.2.2.6 folder in a **path that does not contain any spaces.** This may make a difference in whether it will run or not.

If no luck, please send error.

**Comment by isolver** [comment]
closing, as I understand that it now works fine for Mark. 
@g-no, have you had a chance to try using the MarkWrite_v0.2.2.x.exe standalone MarkWrite app to see that it runs on your PC(s) as well?
