### ISSUE TITLE
import markwrite fails when using WinPython's Spyder IDE and run via an ipython console.

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#152]
See recent comment in issue #134. This issue is for what I think the current problem is related to, and should supersede issue #134 (i.e. #134 can be closed now IMO).

**Comment by isolver** [comment]
More details, copied from #134:

when testing "import markwrite" within a python file being edited and launching using the WinPython/Spyder.exe:
- **WORKS**: Run the file with the Spyder Run Settings Console Option set to  **"Execute in an external System terminal"** 
- **FAILS**:Run the file with the Spyder Run Settings Console Option set to  **"Execute in current Python or IPython console"**:

```
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> runfile('D:/Dropbox/OpenHandWriteDistribution/OpenHandWrite/WinPython/settings/.spyder2/temp.py', wdir='D:/Dropbox/OpenHandWriteDistribution/OpenHandWrite/WinPython/settings/.spyder2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Dropbox\OpenHandWriteDistribution\OpenHandWrite\WinPython\python-2.7.10.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)
  File "D:\Dropbox\OpenHandWriteDistribution\OpenHandWrite\WinPython\python-2.7.10.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "D:/Dropbox/OpenHandWriteDistribution/OpenHandWrite/WinPython/settings/.spyder2/temp.py", line 7, in <module>
    import markwrite
SystemError: NULL result without error in PyObject_Call
```
-  **FAILS**: Run the file with the Spyder Run Settings Console Option set to  **"Execute in new dedicated Python console"**:

```
Traceback (most recent call last):
  File "D:\Dropbox\OpenHandWriteDistribution\OpenHandWrite\WinPython\settings\.spyder2\temp.py", line 7, in <module>
    import markwrite
  File "D:\Dropbox\OpenHandWriteDistribution\OpenHandWrite\WinPython\python-2.7.10.amd64\lib\site-packages\markwrite-0.2.2.1-py2.7.egg\markwrite\__init__.py", line 36, in <module>
    writePickle(appdirs.user_config_dir,u'usersettings.pkl', SETTINGS)
  File "D:\Dropbox\OpenHandWriteDistribution\OpenHandWrite\WinPython\python-2.7.10.amd64\lib\site-packages\markwrite-0.2.2.1-py2.7.egg\markwrite\file_io.py", line 362, in writePickle
    if isinstance(v,QtCore.QString):
AttributeError: 'module' object has no attribute 'QString'
```

---

There are also issues when using "import markwrite" from within the Spyder embedded ipython console tab:

**FAILS**: 

```
import markwrite

Traceback (most recent call last):

  File "<ipython-input-1-c9d7fa9925c3>", line 1, in <module>
    import markwrite

SystemError: NULL result without error in PyObject_Call
```

Not sure if it is related or not, but the following is printed to the Spyder 'Console' tab after you do the markwrite import in ipython:

```
exception UnsupportedOperation('IOStream has no fileno.',) while fixing up sys.stdout and sys.stderr
```

**Comment by Mark-Torrance** [comment]
If you ignore the HDF5 error then, yes, this is Spyder-specific. ipython console, launched directly from IPython Qt Console.exe works...

``` python
import os

os.environ["HDF5_DISABLE_VERSION_CHECK"] = "2". 

import markwrite

markwrite
Out[5]: <module 'markwrite' from 'C:\openWrite\OpenHandWrite\WinPython\python-2.7.10.amd64\lib\site-packages\markwrite-0.2.2.1-py2.7.egg\markwrite\__init__.pyc'>
```

but both ipython and non-ipython consoles in Spyder don't find markwrite (or something). This is oridinary python interpreter in Spyder:

``` Python
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ["HDF5_DISABLE_VERSION_CHECK"] = "2"
>>> import markwrite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: NULL result without error in PyObject_Call
```

**Comment by isolver** [comment]
> but both ipython and non-ipython consoles in Spyder don't find markwrite (or something). This is oridinary python interpreter in Spyder:

``` Python
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ["HDF5_DISABLE_VERSION_CHECK"] = "2"
>>> import markwrite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: NULL result without error in PyObject_Call
```

I found the same, and also noticed that the following is printed to the Spyder 'Console' tab after you do the markwrite import in ipython:

```
exception UnsupportedOperation('IOStream has no fileno.',) while fixing up sys.stdout and sys.stderr
```

**Comment by isolver** [comment]
The above issue actually seems to stem from markwrite **init**.py readPickle() call; accessing the QtCore.QtString class seems to cause issues when run in spyder+ipython, causing the "SystemError: NULL result without error in PyObject_Call" error. SO I seem to be able to get around that one by changing the code a bit. More testing needed.

However, there seem to be multiple issues going on when using the WinPython Spyder to run MarkWrite. For example:
- if the MarkWrite GUI app launcher script is run from Spyder (MarkWrite/runapp.py), it starts fine, but when you select the hdf5 DV variables to use for trial start / end, an error is raised stating that .pyQtObject() method does not exist for type tuple!! So obviously Spyder seems to also be using a different version of pyqt than what pyqtgraph uses when launched from command line directly with python.

What a mess.  I think there must be some incompatibilities between some of the libraries spyder is using, like ipython and pyqt. 

I may try getting the latest WinPython 2.7, install missing packages, and trying this all fresh. Maybe a 'clean' WinPython build will fix all these crossed wires!

**Comment by isolver** [comment]
Last update for tonight. ;)

I think I have everything working via Spyder and when using winpython cmd prompt without the need to manually update any env. variables etc. By everything, I mean I can run the following in Spyder (using ipython console or python console) as well as via .bat files:
- MarkWrite GUI app: OpenHandWrite/MarkWrite/runapp.py
- hdf5 reader example: OpenHandWrite/examples/hdf2txt.py
- batch report gen demo: OpenHandWrite/examples/batchreportgen.py

I can also type "import markwrite" into either Spyder python console type and it will not crash.

Above was done by just making a few changes to the Markwrite source and updating the WinPython.ini file. I will do a new build Monday am my time and send you a download URL when ready.

Hopefully that is that for now. 

I will go onto working on the MarkWrite standalone exe issue Monday afternoon / Tuesday.

**Comment by Mark-Torrance** [comment]
Excellent. Looking forward to testing this.

In the existing distro, I've checked that all of the imports in ExperimentTemplate/run.py will import from within Spyder, and they do.

**Comment by isolver** [comment]
> In the existing distro, I've checked that all of the imports in ExperimentTemplate/run.py will import from within Spyder, and they do.

Great; thanks for testing that out.
