### ISSUE TITLE
01 Feb distro testing...

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#154]
Just producing a checklist, which i'll then...er...check:
- [x] MarkWrite GUI opens from bat and all selection and segmentation actions work
- [x] Report saving from within GUI works
- [x] Project saving and reopening from within GUI works
- [x] Batch report creation runs from bat and works
- [x] MarkWrite package imports successfully in Spyder, with iPython console
- [x] batch report runs successfully from within Spyder
- [x] ExperimentTemplate/run.py runs from bat
- [x] ExperimentTemplate/run.py runs from within Spyder
- [x] Builder example runs from bat
- [ ] check experiment template with both medium and large intuos tablets

**Comment by g-no** [comment]
0.2.2.8
- [x] MarkWrite GUI opens from bat and all selection and segmentation actions work
- [x] opens from bat and all selection and segmentation actions work (in OHW: MW and GW [ExpTempl])
- [x] Report saving from within GUI works
- [x] Project saving and reopening from within GUI works
- [ ] [not tested] Batch report creation runs from bat and works
- [ ] [not tested] MarkWrite package imports successfully in Spyder, with iPython console
- [ ] [not tested] batch report runs successfully from within Spyder
- [ ] [not tested] ExperimentTemplate/run.py runs from bat
- [ ] [not tested] ExperimentTemplate/run.py runs from within Spyder
- [ ] [not tested] Builder example runs from bat

**Comment by g-no** [comment]
This is old stuff, will just close it.
