### ISSUE TITLE
Don't move mouse pointer to "cancel" button in file processing dialogues

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#158]
Feel free to move this to the next milestone if it's not a quick fix but....

When batch processing files a progress dialogue with a cancel button appears. That's good. The cursor moves to the cancel. That's bad because it effectively stops you don't anything else until that batch processing has finished.

**Comment by isolver** [comment]
This is only an issue when doing batch file processing I believe.

So I have removed the progress dialog from appearing at all when a report is being generated using a custom script,  it only appears when using MarkWrite GUI.

Progress for batch report generation is now given by printing to the console.
