### ISSUE TITLE
Support MarkWrite Project Saving / Loading

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#16]
Projects should be able to be saved to a file and reopened later, resaved, ....
"Save As..." support might also be nice.

**Comment by Mark-Torrance** [comment]
We've agreed to demote this, right?

**Comment by isolver** [comment]
Yes and comment out related 'placeholder' gui items, which should be an
issue itself and I will create now. ;)

**Comment by isolver** [comment]
Set priority to 1 so it can be used to track status, etc.

**Comment by isolver** [comment]
For an initial implementation, project saving / loading will focus on the projects data, not the state of the markwrite gui when the project was saved. The following will be saved to a markwrite project file, allowing a user to reopen the project at a later date:
- [ ] project creation time
- [ ] last modified/saved time
- [x] name of original data file opened in the project.
- [x] markwrite sample event table
- [x] existing segment hierarchy 
- [x] misc lookup tables for trial, series, press region, and stroke boundary points

**Comment by Mark-Torrance** [comment]
> not the state of the markwrite gui

Definitely yes. Saving gui settings, windows etc is Priority 3 for me and, I suspect, lots of work for minimal gain.

**Comment by isolver** [comment]
This is now implemented as best as I can tell, so I'm going to close this high level feature request. If you find specific issues / bugs / etc. please create a new issue for each. Thanks.

I added both 'Save' and 'Save As...' actions. 'Save' defaults to 'Save as' for new projects that have not yet been saved as a markwrite project file.

You use the Open action to both:
1. open a pen data file, which creates a new project. 
2. open an existing markwrite project file.
