### ISSUE TITLE
Add series detection for "generic" txyp files with hover (pen up) data

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#161]
Provisionally this is future functionality, but I'm anticipating @g-no saying we need it now (very reasonably because he has data of this sort!).

Current MarkWrite: Files with name "txyp" are assumed to have a special (Eye and Pen) format such that runs (press sequences) end with a single zero pressure event. This information is used to set status to, with status just taking PRESS and FIRST_PRESS values. No series (FIRST_ENTER) or hover (FIRST_HOVER, HOVER) codes are (or could be) inferred. Also data filtering requires series information, so this necessarily needs to be turned off for these files (the MarkWrite default). See #141, #112 and probably others.

However: generic txyp data files, that contain hover data (i.e. zero-pressure sample) _do_ exist and it would be good to be able to process them to give full status information and filtering. This requires
- inferring series boundaries (out of range periods) on the basis of ISI - code already exists for this
- using this to give full status information

To achieve this MarkWrite needs to know that these txyp files contain hover data. I suggest...
1. We require that eye and pen txyp files have the extension"eptxyp" and that all the existing txyp handling logic is associated with this extension.
2. We do the series detection / add status thing for all files with the txyp extension.

I _think_ that that's all pretty easy to do?

**Comment by isolver** [comment]
@g-no We will get this added back, no issue. Give me until Monday please. I am sure I have some, but could you send a couple good examples of your txyp files for testing?

@Mark-Torrance :  as well.
1. So all the existing txyp examples should be renamed to .eptxyp and put in a EPTXYP test_data folder.
2. We need to add test data for Guido's txyp file format.
3. Txyp files we go back to being processed as they were before the changes, however we will update the sample status field appropriately based on pressure data and the ISI generated series boundaries?

**Comment by Mark-Torrance** [comment]
> So all the existing txyp examples should be renamed to eptxyp and put in a EPTXYP test_data folder.

Yes

> We need to add test data for Guido's txyp file format.

Yes

> Txyp files we go back to being processed as they were before the changes, however we will update the sample status field appropriately based on pressure data and the ISI generated series boundaries?

The series-boundary information used for filtering comes from somewhere other than "status" at the moment, doesn't it? You use ISI criteria for series boundaries in hdf5 files as well?

My feeling is that the cleanest way forward would be for all present and future file types to have their own logic for creating the status variable, and then this variable is used to define series boundaries for filtering (not the current situation) and for segmentation actions, and report creation, and anything else that MW does (as is the case currently). However, please say if this involves too much rearranging.

**Comment by isolver** [comment]
> The series-boundary information used for filtering comes from somewhere
> other than "status" at the moment, doesn't it?
> 
> Series information only comes from the status field now, ISI calculation
> and usage was totally removed from the  application based on our
> discussions in the issues.

As discussed, this means only hdf5 files currently have any series
information, xml and txyp files only have run and stroke boundaries and
have no series data since none is provided by the file.

Therefore, if filtering is enabled (default is now that it is off) it
causes artifacts in files other than hdf5 at what would have been ISI based
series boundaries.

> You use ISI criteria for series boundaries in hdf5 files as well?
> 
> No, it was switched from using ISI based series detection to using the
> FIRST_ENTER status bit of sample state, which iohub sets based on a win tab
> msg type iohub receives.
> 
> My feeling is that the cleanest way forward would be for all present and
> future file types to have their own logic for creating the status variable,
> 
> This is how it now currently works.
> - Hdf5: MarkWrite uses state field as saved by iohub at runtime and does
>   not modify sample state field
>   - Xml and txyp: first press and pressed status, used for run
>     boundaries, is set by MarkWrite when file is read. No first enter status is
>     ever set, so no series are ever found.
> 
> and then this variable is used to define series boundaries for filtering
> (not the current situation)
> 
> This is the current situation actually, samples with first enter state bit
> set are used to detect series boundaries. If no series boundary samples
> exist, the whole file is considered to be a single series, and series based
> actions are disabled in the MarkWrite GUI.
> 
> and for segmentation actions, and report creation, and anything else that
> MW does (as is the case currently). However, please say if this involves
> too much rearranging.

So are we going back to the idea that for file types other than hdf5, we
will use ISI thresholding to detect series boundaries? Or do you still want
XML and tptxyp files to not have series boundaries, and only use ISI based
series parsing for the generic txyp file type (guido's files).

My opinion is that we use ISI based Series detection for all file types
other than HDF5. All non hdf5 file types will use ISI based series
detection and update the detected series boundary samples to include
the first enter state. Then all file types will support Series level
grouping in MarkWrite using the sample status field.

**Comment by Mark-Torrance** [comment]
> So are we going back to the idea that for file types other than hdf5, we will use ISI thresholding to detect series boundaries? Or do you still want XML and tptxyp files to not have series boundaries, and only use ISI based series parsing for the generic txyp file type (guido's files).

So we are agreed that we do ISI-threshold -> status (-> filtering etc etc) for generic txyp (Guido's data)

For eptxyp and for xml (handspy) we simply do not have series information. It just isn't available in the data. As soon as the pen is lifted, whether hover or out of range, sampling stops. So status can only take PRESS or FIRST_PRESS,PRESS values. We just don't know anything else. So I think the current strategy for these is the only one that makes any sense. 

[If you do use ISI threshold on eptxyp or handspy data what you actually pick up is mid-run sample-skips. These are, I suppose, sort of series boundaries, but I don't think they correspond to the behaviour that we associate with out of range (i.e. lifting the pen high above the tablet). Much better to just say "we don't know about series boundaries" for these files than to create false positives.]

**Comment by Mark-Torrance** [comment]
So the general strategy as I see it is

If input file contains status data: pass

Else if generic txyp, with hover (zero-pressure sampling): use pressure data to identify run boundaries and ISI thresholding to identify series boundaries and record in Status

Else: use ad hoc rules based on whatever information is available in the data to create an as-sensible-as-possible Status variable

**Comment by isolver** [comment]
On Thu, Feb 4, 2016 at 11:31 AM, Mark Torrance notifications@github.com
wrote:

> Else: use ad hoc rules based on whatever information is available in the
> data to create an as-sensible-as-possible Status variable

However ISI based Series inference can not be one of those ad hoc rules? So
these files will have no series level parsing (no FIRST ENTER sample
status) and will have artifacts in the data if filtering is used.

OK. ;(

**Comment by Mark-Torrance** [comment]
> However ISI based Series inference can not be one of those ad hoc rules? So
> these files will have no series level parsing (no FIRST ENTER sample
> status) and will have artifacts in the data if filtering is used.

Yes, it definitely could be, but not for the particular data that we have (eptxyp and xml). Unless I'm missing something you can't squeeze series information out of these files. It's just not there. 

We could use some other way of quantizing to allow filtering. This is something that could be added as an option (e.g., filter by run). But I'm pretty sure no one who currently has unanalysed E&P or handspy data is bothered about whether or not their data are filtered, and I can't see it having any effect on the conclusions they draw from their data.

> OK. ;(

I just tried to pull that face on my own (wetware) face. It was odd.

**Comment by isolver** [comment]
Can we change the current .txyp files to use an extension something like
.epd, (eye pen data) or .epdf (eye pen data format) instead of .eptxyp?

I'm worried using .eptxyp looks odd and is a longer file extension than the
standard 3 - 4 characters.

**Comment by Mark-Torrance** [comment]
Odd can be good. And longer extension aren't that uncommon (Spyder calls its projects .spyderproject or something). eptxyp has the advantage of saying exactly what we want it to say.

My concern with creating a shorter name is that it will get confused with another file type. I also don't want to sort of invent a new E&P file. What eptxyp says is "this is a txyp file with the special characteristics imposed on it by collection via E&P, but look you could have collected these data in another way". I'm concerned that if we use .epd or something users are going to start saying "but E&P doesn't give me these files, it just gives me text files".

**Comment by isolver** [comment]
OK

**Comment by isolver** [comment]
done.
