### ISSUE TITLE
Permit changing segment label

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#164]
Allow changing of the segment label (e.g., by right click in segment tree), obviously without affecting children.

**Comment by isolver** [comment]
If you right click a user created segment node in the tree a dialog should appear allowing you to edit the segment label. 

The exception to this are the auto generated L1 Trial Segments. They are considered 'locked', so they can not be deleted and their label can not be changed.

Let me know if this should change, or if it is not working as expected for you.

Thanks.

**Comment by Mark-Torrance** [comment]
Ah, sorry, yes: It's already there and working fine.
