### ISSUE TITLE
Save Plot as Image support

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#167]
Add support for saving any of the three plots (spatial, timeline, selecteddata) as a PNG image.

**Comment by isolver** [comment]
Added via a plot context sensitive popup menu with an "Export" menu item.

**Comment by Mark-Torrance** [comment]
This is working fine for me, and a nice feature. Could we have it on shift+right-click or double right-click or something, though. right click and drag zooms, and now each time I end a zoom action I get the export popup.

**Comment by isolver** [comment]
Good point, will look at fixing this.

**Comment by isolver** [comment]
Fixed. Still use right mouse click to display popup, but will not trigger if click occurs at the end of a mouse drag event.

I also changed the popup menu action  "Export" text  to "Save as Image" since that is the only type of exporting currently supported.

Pls close after you confirm it now works to your liking.

**Comment by Mark-Torrance** [comment]
Tested. Works great. Closing.

**Comment by g-no** [comment]
Saving images works only once!

**Comment by isolver** [comment]
Fixed.
