### ISSUE TITLE
Add stroke points to velocity & accelleration plots

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#169]
Suggested by @g-no:

> For a better overview, it would be cool to have the stroke segmentation points in the acceleration plot,

**Comment by g-no** [comment]
In addition, all graphs/traces in the timeline (horizontal/vertical, velocity & acceleration) have to be aligned. At the moment it's possible to move the velocity trace independant of the horizontal/vertical trace. This should not be possible.

**Comment by isolver** [comment]
moving multitrace bug g-no mentions in last comment to new issue

**Comment by isolver** [comment]
Added boundary points to accel and vel traces, if plotted. 
- Boundary point display setting controls visibility on all plots. 
- Same boundary point color and size are used on all plots.

![va_stroke_points](https://user-images.githubusercontent.com/1795082/35626695-7c3e0c80-0664-11e8-9f75-a59c43e4e6b4.png)

Does this look OK @g-no?
