### ISSUE TITLE
Spatialview viewport bounds too small.

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#170]
Reported by @g-no:

> Moving the contents of "Spatial view": It would be good to be able to move the window a few pixels more that the minima/maxima of the x and y axis, because the dots on the border can't be seen very well.

**Comment by isolver** [comment]
@g-no, do you find this to be a general issue or does it occur after some specific action?

currently you can adjust the view magnification using the mouse wheel: when over the window with your mouse, use your mouse wheel and the view should zoom in or out. Is this useful enough, or do you think there is still a usability issue I should fix?

thanks!

**Comment by g-no** [comment]
If possible, add a padding of 5 pixels on all sides.

**Comment by isolver** [comment]
Fixed, spatial view now has 5 pixel padding around plot

**Comment by isolver** [comment]
Not sure this was ever really fixed properly... working on it.

**Comment by isolver** [comment]
really fixed it this time I think.
