### ISSUE TITLE
prev_ next_penpress_time in segment report

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#174]
These currently give wrong values. The following repair works (line 97 onwards in segment report). searchsorted returns the index of the nonzero_pressure_ixs not that actual nonzero_pressure_ix

``` python
                if start_index>0:
                    prev_nonzero_ix = nonzero_pressure_ixs[np.searchsorted(nonzero_pressure_ixs, start_index, side='left')-1]
                    prev_penpress_time = pendata['time'][prev_nonzero_ix]
                if end_index < pointcount-1:
                    next_nonzero_ix = nonzero_pressure_ixs[np.searchsorted(nonzero_pressure_ixs, end_index, side='left')+1]
                    next_penpress_time = pendata['time'][next_nonzero_ix]

```

**Comment by isolver** [comment]
Hi Mark,

Sorry, Not clear on what you want me to do here if you already found a fix?

Thanks!

**Comment by Mark-Torrance** [comment]
Sorry, just implement the fix in the code in the repository. I don't know how to do this (and also would be scared of messing something up). I should have one or two more custom reports to add in the next couple of days, so maybe just wait till them.

**Comment by isolver** [comment]
OK.

Note I will be away from April 11th - 18th, so adding the reports to github
will likely have to be added after that if that is OK.

**Comment by Mark-Torrance** [comment]
Fine. Thanks.

**Comment by isolver** [comment]
I quickly changed the [segment report code](https://github.com/isolver/OpenHandWrite/blob/master/src/markwrite/markwrite/reports/segment.py) online on github. Can you get the updated file and replace your local copy with it to check that it works OK for you?
