### ISSUE TITLE
custom reports menu run wrong custom report

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#175]
From @Mark-Torrance : 

> In the GUI I can see its name in the export menu. However, when I select it runs RawSampleDataReportExporter instead (i.e. the other class in customreports.py).

**Comment by Mark-Torrance** [comment]
I've tested this again, and it remains an issue in most recent distro (0.2.2.11). This is the custom reports script that I tested with.

[customreports.zip](https://github.com/isolver/OpenHandWrite/files/213589/customreports.zip)

**Comment by isolver** [comment]
Fixed. Pls test and close if it works for you too.

To test you can [download the latest standalone exe version](https://drive.google.com/file/d/0B-qFhchxISOSY3E0bzF1aWZiZVU/view?usp=sharing), which is  MarkWrite_v0.2.2.12.exe.
1. Upack self extracting folder; top level folder created is called MarkWrite_v0.2.2.12
2. Copy your customreports.py into the same folder as the MarkWrite.exe app, i.e. MarkWrite_v0.2.2.12\MarkWrite.

**Comment by g-no** [comment]
When using v.0.3.2 and customreports.py (2017-10-15) I have five options:
- Pen Sample Report
- Sement Level Report
- Detailed Sement Report
- Raw Sample Data Report
- Raw Sample Data Report Plus Segs Report

I get the correct reports, so: testing done, issue fixed.
