### ISSUE TITLE
Read in trial data from a text file

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#177]
Currently MW can create trial-level segments from HDF5 (GetWrite) data files that contain trial data. Trials are not recognised in any other input data (txyp, hdf5).

It would be good if this were possible (specifically to permit analysis of data already collected by @g-no.

If we created a text files that looked something vaguely like this (or whatever works):
## Trial1_start, time

t,x,y,p 
t,x,y,p
....lots more samples
## Trail2_start, time

 t,x,y,p
t,x,y,p
etc.

would it be possible to create a data importer in MW that reads it and segments by trials? If so, exactly what information is needed in the text file to achieve this?

**Comment by isolver** [comment]
This is doable for sure. To be consistent with the current app logic, I would suggest we implement the trial parsing around the general idea of trial variables.

If the trial information is going to be embedded in one or more of the existing file formats, then we should just add support for this to the existing importer(s). We could add support for 2 new row 'types' in the data file:
1.  trial variable names row: Near the start of the file, with the file only containing one row of this type. This would be used in the same way the hdf5 condition variables table column names are used.
   
    Format something like:
        !TRIAL_COND_NAMES var_label_1 var_label_2 .....  var_label_n
2. trial variable value rows: Can be anywhere in the file following the trial variable names row defined above. Each row would be used in the same way each row of  the hdf5 condition variables table is used.
   
   Format something like:
        !TRIAL_COND_VALUES var_1_value var_2_value .....  var_n_value

This way all the functionality in MarkWrite around parsing samples into trials and associating trial level condition values to each would not need to change at all.

Thoughts?

**Comment by Mark-Torrance** [comment]
That's exactly the sort of thing that I had in mind. You could just add that to the txyp importer (for generic txyp files)?

@gnot how urgent is this?
@isolver how many hours to do this?

I'm aware that we don't yet have a report exporter that makes use of these trial variables. This would be good reason for me to get on and do this. However, I would prefer to leave it until July.

**Comment by Mark-Torrance** [comment]
Good. I suggest we hard-code the tag that indicates trial start (the one that's used for top-level segmentation). Currently there's a dialogue box when hdf5 files import, but this isn't needed here.

Or, better, use var_label_1 must represent the trial-start marker.

!TRIAL_COND_NAMES var_label_1 var_label_2 ..... var_label_n

@g-no and I will create an example file and then maybe we can action this sooner rather than later

**Comment by g-no** [comment]
I'd prefer a single trial variable names row. 
var1 = Participant
var2 = trial number
var3 = trial name
Start time is always 0
I'd need something like this in about two weeks or earlier, please.

**Comment by isolver** [comment]
MarkWrite currently uses project setting values to find the condition
variable that should be used for trial start and trial end times. It would
be best if we just used this same logic for !TRIAL_COND lines in a txyp
file. By best I mean a) most consistent user experience, b) quickest way to
implement the code. ;)

**Comment by isolver** [comment]
Implemented this in MarkWrite for txyp files. tyxp files can now include data needed to create condition variables table data for a project, which will also be used to do l1 trial segmentation of the data file.

What is expected:

txyp file format is as before, but 2 new line types are supported, a line that starts with '!TRIAL_CV_LABELS', and lines that start with '!TRIAL_CV_VALUES'.

!TRIAL_CV_LABELS gives the name of each column to use when creating the condition variables table for the project. This line can occur only once in a txyp file, and must occur after the first line of the file, but before the first !TRIAL_CV_VALUES line. For l1 trial segmentation, two of the labels must be DV_TRIAL_START and DV_TRIAL_END.

Example:

```
!TRIAL_CV_LABELS Part_ID Trial_ID Trial_Word DV_TRIAL_START DV_TRIAL_END
```

A !TRIAL_CV_VALUES line is used to provide the trial condition value for one trial within the txyp file. If there are T lines starting with !TRIAL_CV_VALUES, then it is assumed the file contains data for T trials. The 
 DV_TRIAL_START and DV_TRIAL_END values in each line are used split the txyp file samples into trials.

Examples:

```
!TRIAL_CV_VALUES 5-02-w 02 Kind 6224.000 13198.000
!TRIAL_CV_VALUES 5-02-w 03 Garten 17644.000 27566.000
```

See the MarkWrite\test_data\TXYP\session.txyp file for an example of a txyp file that contains data for  2 trials.

**Comment by isolver** [comment]
MarkWrite version bumped to 0.2.3.

I have committed all source changes and also made a build of the standalone MarkWrite app, **MarkWrite_v0.2.3.exe**, which can be downloaded from the usual Google SHARE drive. 

Closing issue. Please reopen if it is not functioning as desired / expected.

Thanks.
