### ISSUE TITLE
alternative source for stroke detection (based on Y-minima and -maxima)

### ISSUE THREAD

**Issue by g-no** [isolver/OpenHandWrite#179]
An alternative and very basic approach (selectabel in the Stroke Detection settings) would be to set stroke boundaries at every local Y-minimum and maximum (using the same sub settings as the stroke detection based on XY-velocity).

**Comment by g-no** [comment]
Changed this from P3 to P1

**Comment by isolver** [comment]
@g-no: 
> boundaries at every local Y-minimum and maximum ...

do you mean y *position* min / max, or y-only velocity data? Thanks!

**Comment by g-no** [comment]
position

**Comment by isolver** [comment]
Implemented. Added 2 new settings:

* Use Sample Field: Select pen sample field to be used for local min / max detection. Options: 'xy_velocity' or 'y_filtered'.
* Detect Peaks / Valleys: Select whether local min, max, or both should be detected. Options: 'Minima' or 'Maxima' or 'Minima & Maxima'

Defaults are 'xy_velocity' and 'Minima'; which results in existing parser alg being used.

To instead use local Y-minimum and maximum, use 'y_filtered' and 'Minima & Maxima'.

**Comment by g-no** [comment]
Cool!
