### ISSUE TITLE
adjust all settings for Experment Template in one file (GetWrite)

### ISSUE THREAD

**Issue by g-no** [isolver/OpenHandWrite#180]
We had an e-mail conversation about this some time ago. The solutions proposed by Sol are great and won't need too much time. I'll quote it here:

> SOL: The items related to the digital pen graphics could be made as arguments to the relevant classes, allowing these things to be changed from the experiment script where the classes are initialized. It could be taken a step further and these options could be all made variables that are read from the experiment constants.py file, like the EXP_NAME, DEFAULT_SCREEN_COLOR and other are already.This would not be very hard / time consuming to do.
> [...] In an hour of time, things could be changed so that the following could all be set by changing variable values in the experiment templates constants.py file: pen colour, line thickness, tiltline color (or None to indicate to not display it at all), hovering pen tip color (or None to indicate to not display it at all), pressed pen tip color (or None to indicate to not display it at all), pen tip type: gauss, circle, or image types could be supported.
> [...] This would result in everything Guido mentioned being set in either the constants.py file or in the condition variables .xlsx file that is selected at session start, as they already are.

This would be great!

**Comment by g-no** [comment]
Is this done? If that's still possible, this would be great.

**Comment by isolver** [comment]
@g-no, for this issue, can we define the requirements a bit more? Is this good:

Allow the following experiment settings to be defined in the constants.py file for the getwrite\experiments\ExperimentTemplate example:

Pen Trace Stim
-----------------

 - [x] pen trace color
 - [x] pen trace line thickness
 - [x] pen trace opacity

Pen Point / Position Stim
---------------------------

 - [x] tiltline color
 - [x] tiltline thickness
 - [x] hovering pen tip color
 - [x] pressed pen tip color
 - [x] pen tip minimum size
 - [x] pen tip size range

 - [ ]  pen tip type: gauss, circle, or image types could be supported.

**Comment by isolver** [comment]
I'm generalizing this to be used in the getwrite\wintabtest as well.

**Comment by isolver** [comment]
@g-no, I have done (and tested) the above additions to the constants file. The only one remaining is the pen tip type, which is currently always the Gaussian type. Do you want me to add an option to use a standard circle or image instead, or is this not so important? Thank you.

**Comment by isolver** [comment]
@g-no, can we close this or should we keep it open for now and switch delivery date?

**Comment by g-no** [comment]
That's fine! I'll close the issue.
