### ISSUE TITLE
remember the path of the last file opened

### ISSUE THREAD

**Issue by g-no** [isolver/OpenHandWrite#181]
Most of the times I have to open several files from the same folder one after the other. If I click on "open" I always have to start with the markwrite root folder. It would be nice, if the path of the last file opened could be reopened.

**Comment by isolver** [comment]
fixed in 0.3.5

**Comment by g-no** [comment]
If I open the "file | open" dialogue and cancel it, the path previously saved is lost and replaced by the default path.

**Comment by isolver** [comment]
Fixed.
