### ISSUE TITLE
remember last segment in segment tree

### ISSUE THREAD

**Issue by g-no** [isolver/OpenHandWrite#182]
When I delete a (sub-)segment from the segment tree, the segement tree jumps to the first element. It would be better if the selection would stay with the parent element of the element just deleted (so I wouldn't have to scroll down a lot).

**Comment by isolver** [comment]
good point.

**Comment by g-no** [comment]
In addition, the following would be nice:
If I double-click on a word (or something) in Spatial View, the focus in Segment Tree is set automtically to this element.

**Comment by isolver** [comment]
creating new issue for @g-no last comment

**Comment by isolver** [comment]
Select parent segment on seg delete is fixed in 0.3.5
