### ISSUE TITLE
allow child segment to share all pen points with parent

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#186]
Currently, a child segment must contain a subset of the pen points from the parent; they can not share all pen points. This causes issues when different levels of segment parsing require a child to be == its parent. For example, a sentence with only 1 word may need a sentence level segment and word level segment that have the same set of pen points.

Suggested fix is to relax the segment hierarchy rules and allow a child segment to have the same point set as it's direct parent. 

@g-no, @Mark-Torrance, this change will be committed end of week unless you let me know that it is a bad idea. ;)

**Comment by isolver** [comment]
fixed in 0.3.4

**Comment by g-no** [comment]
Yes, it must be possible to have child == parent.
