### ISSUE TITLE
segments with 1 sample crash detailed segment report

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#187]
Sometimes a segment is created with only 1 pen sample in it. The detailed segment report includes columns that are based on the difference between consecutive sample and assumes a segment will have >= 2 at minimum.

The fix is to update the detailed segment report to detect segments with only 1 sample and set necessary variables to a default or empty value. Effected detailed segment report columns are:

- x_disp
- y_disp
- xy_disp
- hover_xy_disp
- press_xy_disp
- pause_counts
- duration2             
- hovertime 
- presstime
- not_presstime
- outrange_time

I've implemented this fix, which currently sets the above columns to 0 for segments with 1 sample. @g-no , @Mark-Torrance please comment if you would like me to change the fix, otherwise it will be committed end of week.

**Comment by isolver** [comment]
Note, fix uses cls.missingval instead of 0 for default value

**Comment by isolver** [comment]
fixed in 0.3.4

**Comment by g-no** [comment]
good!
