### ISSUE TITLE
double click spatial view should select segment

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#189]
from @g-no:

> In addition, the following would be nice:
> If I double-click on a word (or something) in Spatial View, the focus in Segment Tree is set automtically to > this element.

I guess selection alg should be:
   - find nearest pen point to mouse click pos in spatial view
   - if point is associated with a segment, select lowest level seg associated in seg tree.
  - if point is not associated with segment, do nothing??

**Comment by isolver** [comment]
#165 maybe related

**Comment by g-no** [comment]
at the bottom of priority 1, may be set to P2 if capacities run out

**Comment by isolver** [comment]
fixed in 0.3.8

**Comment by g-no** [comment]
can this be closed?

**Comment by isolver** [comment]
I think so, but will test today and close after.

**Comment by isolver** [comment]
Hum, can't seem to get it to work so I'll look into it.

**Comment by isolver** [comment]
It works, but if the nearest pen point to the double click is **not** yet part of a segment, then nothing is selected. @g-no , is this OK ?

**Comment by g-no** [comment]
Yes, this is OK!

Would it be very laborious to implement the same behavior for the Timeline?

**Comment by isolver** [comment]
Probably not too bad. Will close this and open an new bug (Priority 2 for now).
