### ISSUE TITLE
Differentiate pen data points where pressure == 0 vs > 0.  

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#19]
Thoughts on what should be implemented here:
- use different color in GUI View Widgets for pen points where pressure == 0 vs > 0
- perhaps project should keep a separate masked array that only contains the points where pressure == 0
- Need to use the pressure value to determine how to auto trim data selection when creating new segments. See issue #13 for more info on this point.

Any other considerations / functional requirements related to the pressure value of pen points?

**Comment by Mark-Torrance** [comment]
use different color in GUI View Widgets for pen points where pressure == 0 vs > 0 YES

perhaps project should keep a separate masked array that only contains the points where pressure == 0 Sorry, editing this: NO I'm not sure that there's a need for this unless it's essential for programming reasons. What we do need is an option to display or not display zero pressure samples in the Spatial View.

**Comment by Mark-Torrance** [comment]
This should be moved to second milestone, I think.

**Comment by isolver** [comment]
Oops, I just implemented it before seeing your post. Now timeline and spatial views use a different color for 0 pressure points than for pressure > 0 points.

Can always revert it if wanted.

**Comment by Mark-Torrance** [comment]
One less thing to do next time.
