### ISSUE TITLE
Support Surface Pro 3

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#190]
Get Surface Pro 3 working with wintab interface; assuming this can actually be done.

**Comment by isolver** [comment]
@g-no: is it just surface pro 3's or also version 4's etc?

**Comment by g-no** [comment]
I assume that if it works for surface pro 3, it'll work for surface 4+ as well. Microsoft [changed from Wacom to N-Trig digitizers](https://www.cnet.com/news/microsoft-acquires-surface-pen-technology-from-n-trig/).

**Comment by isolver** [comment]
Status update on this:

1. Surface Pro 3 + wacom tablet device + wacom driver: WORKS
2. Surface Pro 3 + wacom tablet device + microsoft driver: DEVICE NOT DETECTED
3. Surface Pro 3 + SP3 Pen + wacom driver: DEVICE NOT DETECTED
4. Surface Pro 3 + SP3 Pen + microsoft driver: IOHUB NO EVENTS; PYGLET DEMO OK

Have not been able to find a way to get data from the SP3 pen from within the iohub process. It appears that the microsoft version of the wintab driver does not support passing events to a full screen hidden window like the wacom wintab dll does.

iohub needs to be able to get events at an OS wide level (mouse, keyboard are like this), or from a hidden full screen window it creates (wacom tablet device is like this).

Seems like only option would be to get wintab events from within the psychopy process using the pyglet interface; but this will result in events being timestamped in groups quantized to the retrace interval.

So we are going to try implementing a mouse simulation mode in the iohub wintab device that can be used when actual wintab events can not be received. Will create new issue for the mouse sim.
