### ISSUE TITLE
same text for tooltips as in settings

### ISSUE THREAD

**Issue by g-no** [isolver/OpenHandWrite#193]
Very minor: In the settings dialogue there are descriptions for each keyboard shortcut. The tooltips (button hover) don't contain the same text. The text in the settings dialogue is correct, the tooltips are inconsistent and should take over the text from the settings dialogue.

**Comment by isolver** [comment]
good point

**Comment by isolver** [comment]
set to P1 to track first 6 priority issues from @g-no

**Comment by isolver** [comment]
fixed.
