### ISSUE TITLE
File names for reports

### ISSUE THREAD

**Issue by g-no** [isolver/OpenHandWrite#196]
While saving a Report in previous versions there was automatically a ".txt" attached to the file name and the file name was automatically derived from the imported file. The same for .mwp files.
- [x] offer .txt as file type for reports
- [x] offer .mwp as file type for MarkWrite projects
- [x] suggest file name derived from the imported file (as was previously the case v0.3.2) for reports and projects

**Comment by isolver** [comment]
fixed.
