### ISSUE TITLE
how to handle series with 1 minima

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#212]
@g-no commented:

>  "TODO: HOW TO HANDLE SERIES WITH SINGLE MINIMA": in these cases the 
> first and the last data points in the series can serve. (This is done 
> anyway later in the code, if I understand this correctly, so maybe this 
> step may be moved forward to solve the problem?)  
>

**Comment by isolver** [comment]
My concern with doing this, is that we are therefore making any series with min thesh sample count and with 1 minima a stroke; regardless of its 'quality'.I'm not sure we will be able to classify its type PAUSE vs. MOTION properly anymore. Or is this more a theoretical issue and not one for actual data analysis?

I was wondering if we should use the minima as the stroke start and the series end as the stroke end, but then we have samples that would not belong to any stroke. 

Another idea might be to leave the 1 minima and add the start end end series points, so a series with 1 minima would, to start, be considered a series with 2 possible strokes:

[series_start_index, minima_index]
and
minima_index, series_end_index]

Thoughts?

**Comment by g-no** [comment]
> Another idea might be to leave the 1 minima and add the start end end series points, so a series with 1 minima would, to start, be considered a series with 2 possible strokes:
> [series_start_index, minima_index]
> and
> minima_index, series_end_index]

This sounds like a good solution.

**Comment by isolver** [comment]
This ended up being equal to just using same logic as series with > 1 minima, which already was adding start and end points.
