### ISSUE TITLE
Add new Parser Report

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#217]

**Comment by isolver** [comment]
New report, with columns from current raw sample report with segs plus:

> 'x.fc10',
> 'y.fc10',
> 'x.fc5',
> 'y.fc5',
> 'vxy.fc10',
> 'vxy.fc5',
> 'vxy.fc10.extrema',
> 'vxy.fc5.extrema',
> 'vxy.fc10.minima.dalpha',
> 'series_sample_index',
> 'vxy.fc10.minima.pre',
> 'vxy.fc10.minima.post'

These columns should only be populated if the V&C stroke alg is in use. Otherwise fill with nan value for report.

**Comment by isolver** [comment]
Implemented initial version of report. Needs some sanity testing, but looking good I think. @g-no, can you look at the attached and confirm it has the report format you wanted? I know where are still a couple open issues like the output values a strokes last sample.

[Sample_Velocity_And_Curvature_Stroke_Parser_Report_python_exp_template.txt](https://github.com/isolver/OpenHandWrite/files/3293067/Sample_Velocity_And_Curvature_Stroke_Parser_Report_python_exp_template.txt)

**Comment by g-no** [comment]
I had a quick look and couldn't find any issues :)

**Comment by isolver** [comment]
Closing, will be available in 0.47 release. Please make new issue if you find any problems. Thanks.
