### ISSUE TITLE
which version ofPsychopy?

### ISSUE THREAD

**Issue by simon-more** [isolver/OpenHandWrite#220]
Ok, I won't take account the MS Surface pro 6, In first time I will try OHW with an "Wacom intuos large". and in first time x,y will be sufficient

Which version of psychopy is the good one to use OHW

with psychopy 3.05 ( python 2.7), I had some trouble running wintab test 

`from psychopy.iohub import launchHubServer, EventConstants`

this is fixed with with
` from psychopy.iohub.constants import...`

but now it's with keyEvent.Key.lower() :
`phkey = keyEvent.Key.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
`

I imagine this is differences beetween different version of psychopy.

I haven't seen on a read mea recommanded version. Which one do you recommand?

**Comment by isolver** [comment]
Everything you need, including the Python environment and package versions OHW works, with from the releases page:

https://github.com/isolver/OpenHandWrite/releases

OHW is not compatible with current versions of PyschoPy, or Python 3 for that matter.

**Comment by Mark-Torrance** [comment]
Quick additional wider comment, but relevant here: 

Simon, it's great that you are using this. You currently have four options for creating experiments with wacom tablets via OHW. 

- Use PsychoPy Builder. There's an example with OHW. To be honest, though, we don't know of anyone who has gone down that route - it relies on a lot of custom code - and it would not be my choice.

- Use the Template Experiment that comes with OHW. This allows experiment programming using keywords in a spreadsheet (excel / CSV). 

- Use simplePET. This is a much more flexible development from Template Experiment that allows multiple trial "stages", keyboard input, gaze-contingent display, mouse input, and so forth. So everything that you can do in raw PsychoPy, and more (well, not quite - but you get the idea). What it can't do (easily, at least) is conditional branching. So if subject does x they go to display A, but if they do y they go to display B. You don't currently have access to this, but it will be ready for use in the next few weeks and it would great to have some using it and giving feedback.

- Program your own experiment using ioHub / PsychoPy and the wintab interface that comes with OHW. We have one PhD student here at NTU who ran all his PhD research (including EEG) doing this.

**Comment by simon-more** [comment]
Hi,

I'm in the way for the 4th option, programming my own experiment but using some parts of OHW's scripts.

To do simple modification on your scripts, I need to know which version of Psychopy is used.

For example, if I want to modify the color of the trace in Wintab_test, how to do?

I have to check how works "psychopy.iohub.client.wintabtablet.PenPositionStim" but  for which version of psychopy?

I founded OpenHandWrite\WinPython\python-2.7.10.amd64\Lib\site-packages\PsychoPy-1.83.2-py2.7.egg  

So now I'm looking in wintabtablet of psychopy 1.83.2.

**Comment by isolver** [comment]
You are looking in the right place from the sounds of it.
