### ISSUE TITLE
Warning in monitor center

### ISSUE THREAD

**Issue by Krissi001** [isolver/OpenHandWrite#222]
OS: mcOS Big Sur 11.0.1
PsychoPy version: 2020.2.10

When I wanted to delete the last monitor calibration in the monitor centre, this error code appears:

Traceback (most recent call last):
File „/Volumes/PsychoPy-2020.2.10/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/monitors/MonitorCenter.py“, line 720, in onDeleteCalib
File „/Volumes/PsychoPy-2020.2.10/PsychoPy.app/Contents/Resources/lib/python3.6/psychopy/monitors/calibTools.py“, line 525, in delCalib
ValueError: list.remove(x): x not in list

What can I do? The reason for this new calibration is this Warning which appears every time I want to start my experiment:
WARNING: User requested fullscreen with size [1024 768], but screen is actually [1440,900]. Using actual size

Maybe someone could help me? Thank you very much.

**Comment by Mark-Torrance** [comment]
Krissi, this is a PsychoPy issue rather than something specific to the OpenHandWrite code, I think. Probably best directed here https://discourse.psychopy.org/
