### ISSUE TITLE
Pen sample report is empty if the condition file contains Chinese characters

### ISSUE THREAD

**Issue by syu-id** [isolver/OpenHandWrite#223]
Thank you for this great project! We are developing an experiment to record the handwriting of Chinese characters.
We are using the latest OpenHandWrite release (v0.4.7) and have built a test experiment based on the Builder example (`getwrite\experiments\Builder_AV_Example`).

## The problem

In our tests, the pen sample report will be empty if the Excel condition file contains Chinese characters.
Could you support more character sets such as Chinese? Variables in the condition file can be very important for data analysis.

## Steps to reproduce

To reproduce, you can use the `Builder_AV_Example` and edit the condition file to add a column with some Chinese values.
Then collect some data, and export the pen sample report with MarkWrite.

- Example condition file: [trial_conditions.xlsx](https://github.com/isolver/OpenHandWrite/files/5709211/trial_conditions.xlsx)
- Example hdf5 file (zipped): [test1.zip](https://github.com/isolver/OpenHandWrite/files/5709232/test1.zip)

![Example condition file](https://user-images.githubusercontent.com/1129506/102485449-fbea8200-40aa-11eb-9dfb-2e29a28df659.png)

The report is empty with only table headers:
![image](https://user-images.githubusercontent.com/1129506/102486548-8b446500-40ac-11eb-8cfe-5c637f24aa86.png)

Best,
Eric

**Comment by isolver** [comment]
Thanks for reporting the issue and providing such an excellent description of the bug.

I can reproduce the issue using the test hdf5 file you included and v 0.4.8 of the source code. I'll try to fix the problem by the new year.

The python error that is occurring is:

```
  File "...\markwrite-0.4.8-py2.7.egg\markwrite\reports\__init__.py", line 334, in export
    f.write(rowformatstr.format(*row))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
```

**Comment by isolver** [comment]
Release [0.4.9b](https://github.com/isolver/OpenHandWrite/releases/tag/0.4.9-beta) has been created. Please let me know if you run into any issues. Thanks.

**Comment by syu-id** [comment]
Thank you so much for the fix! Now pen sample reports are exported with Chinese characters.

![image](https://user-images.githubusercontent.com/1129506/102789934-1fce0080-43e8-11eb-8fdf-840bb0c6ce06.png)
