### ISSUE TITLE
Builder example saves trial onset times as integer type

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#224]
The following hdf5 was created with an experiment based on `\getwrite\experiments\BuilderExample`

[00_Handwriting-main_2020_Dec_18_1756.zip](https://github.com/isolver/OpenHandWrite/files/5715442/00_Handwriting-main_2020_Dec_18_1756.zip)

In the EXP_CV_1 table DV_TRIAL_START and DV_TRIAL_END store trial onset and offset times. When opened in R these appear as integer type, and so are only to 1 second accuracy. I've checked in MarkWrite, and although times are displayed to three decimal places, they appear just as whole numbers. This suggests that the issue is with how the Builder example is treating trial onset and offset times (and not to do with how I'm importing hdf5 files). Tablet sample times are stored correctly. So this appears to be just an issue with trials.

**Comment by Mark-Torrance** [comment]
Ah, ok, easy solution (thanks Shaoyun): The data type of DV_TRIAL_START and DV_TRIAL_END appears to be determined by the placeholder values in the condition file. Changing these placeholders to -1.1, the timestamps seem to be correct now.

**Comment by isolver** [comment]
This is, for better or worse, expected behaviour. Each column's data type is determined by the first row of data. We could change it so that a number column is always saved as a float if you think that would be more user friendly.

**Comment by Mark-Torrance** [comment]
Thanks Sol. Sorry. We worked this out :) I think we leave it as it is.
