### ISSUE TITLE
  RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by Luztw** [isolver/OpenHandWrite#228]
Thanks to whom contributed to this project,  this is an amazing if I could use it in my Chinese hand writing experiment. But  I meet an  error message in the very beginning stage in running "build_ohw_dist.bat ". I am new to python script, so I don't have an idea about this error below: 

 File "D:\OpenHandWrite-0.4.9-beta\OpenHandWrite-0.4.9-beta\src\markwrite\markwrite\util.py", line 101, in <module>
    for k,v in SAMPLE_STATES.items():
RuntimeError: dictionary changed size during iteration

Any help is greatly appreciated.

**Comment by Mark-Torrance** [comment]
We're very happy that you plan to use this.

Your strategy for getting started is to download and extract the full OHW distribution linked here https://github.com/isolver/OpenHandWrite/releases/tag/0.4.9-beta. Also note the temporary custom-report fix, if you are likely to want to use that report. Then plug in you digitising tablet and check the you can run `Run_TestWinTab.bat`. Then explore either the PsychoPy Builder or TemplateExperiment examples to see how to set up your own experiment.

The bat file that you are trying to run is not part of the distribution.

**Comment by Luztw** [comment]
> We're very happy that you plan to use this.
> 
> Your strategy for getting started is to download and extract the full OHW distribution linked here https://github.com/isolver/OpenHandWrite/releases/tag/0.4.9-beta. Also note the temporary custom-report fix, if you are likely to want to use that report. Then plug in you digitising tablet and check the you can run `Run_TestWinTab.bat`. Then explore either the PsychoPy Builder or TemplateExperiment examples to see how to set up your own experiment.
> 
> The bat file that you are trying to run is not part of the distribution.

It is really appreciate for your help. We run it and it works. And we also found many information are already written in  the wiki. We are reading these document. Thank a lot.   Meichun
