### ISSUE TITLE
Pen sample time stamps

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#23]
Both supported input file formats provide each pen sample time in msec, and they can be huge. For example, the 66.xml file's first pen point time is 40527815441.
1. When loading a data file, should all the pen sample times be normalized (starting at 0) for use in the application?
2. Should this operation be optional, set by the user via the project setting dialog? If so, what do you think the prefered default state for it would be, enabled?

If you think this should be added, please set priority tag accordingly. If you do not, please set to won't fix and close issue.  

Thanks!

**Comment by Mark-Torrance** [comment]
1. Yes, should be normalised (I now understand what you meant when you asked this before).
2. Should not be optional.

**Comment by isolver** [comment]
Another thought, I guess both the original time and normalized times may want to be kept.
For example when working within the app GUI the normalized time maybe prefered, but when creating a pen sample level report, the time should probably match the time of the input file sample?

**Comment by Mark-Torrance** [comment]
I don't see any reason to retain the original clock time. I also don't see why they didn't normalise when originally collecting the data!

**Comment by isolver** [comment]
Only reason I can see if if they need to somehow sync the output report
data with other data that was saved using the same time base.

If / when iohub supports these devices, then this becomes a non-issue since
time stamps start at 0, which is set when the experiment starts.

**Comment by Mark-Torrance** [comment]
Ah yes. It's possible (probable) also that in the future the capture file will include events that aren't samples - system messages and so forth.

So for input files which have (or are wrangled into) one row per event (where events are sometimes but not always pen samples):
1. Index all events (rows) in the event file from 0 to n where n is total number of events (rows).
2. Retain this event index the (sample-only) data that are passed into MarkWrite for segmentation etc
3. Normalise time.
4. Include the event index in output files (and maybe also show in segment summary view, along with segment duration in ms).

This will allow matching back to the original event file, but without having to pass stupidly long clock times to the program.

Does that work?

**Comment by isolver** [comment]
Sounds good.

Can we also make the normalized time stamps as float sec.msec format
instead of int msec? That way they will be using the same time unit (float
seconds) as what all psychopy / psychopy.iohub times are in, saving
possible headaches in the future.

**Comment by Mark-Torrance** [comment]
> Can we also make the normalized time stamps as float sec.msec format instead of int msec? That way they will be using the same time unit (float seconds) as what all psychopy / psychopy.iohub times are in, saving possible headaches in the future.

YES

**Comment by isolver** [comment]
Done:
- Time normalization to 0.0 sec done - not optional 
- pen sample index column added to report

It is times like this I love numpy:

``` python
    # pen_data is numpy ndarray from loaded data file
    self._original_timebase_offset=pen_data[0]['time']
    pen_data['time']-=self._original_timebase_offset
     pen_data['time']=pen_data['time']/1000.0
```

**Comment by Mark-Torrance** [comment]
I’ve been using R a lot recently and this has similar data structures. In the large-data-file-manipulation programs I’ve written in Python I’ve used lists of list [of lists…]. I really should start using arrays in Python, which would also help keep my head in the right place when using R.

**Comment by isolver** [comment]
R seems to be taking over the world for stats. I have never found time to do anything more than look at it at a very high level, never used it for any real project.

Python -> R integration seems to be a hot topic these days as well. IPython Notebook 3.0 has very good R integration I am told.

I should really find the time to learn R to the point of being able to take advantage of it.

**Comment by Mark-Torrance** [comment]
I don’t think you want to “learn” it unless you have an immediate use. It’s pretty much essential for the kinds of stats that I am now using, though, and because it’s so widely used (like Python) googling nearly always gives an answer. The downside of the huge user and contributor base does, is that it can be bewildering. For example, the same function names give you different things depending on which libraries you have installed. Powerful, batteries included, but organic rather than systematic. Someone described it as a Swiss Army chainsaw.
