### ISSUE TITLE
Use cursor keys to move selection in time line?

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#24]
I've been playing some more with the program, and am trying to imagine coding a lot of data. The slow bits are typing in the tag for the selection (not too much of a problem and the taglist should help with) and having to make some quite precise mouse actions to select the next segment in the time line. What I want to be able to do is more or less ignore the timeline (except for fine adjustments) and just look at the spatial and quickly select a segment. I think this would be made much easier if I could move the selection around using the four cursor keys (or something). I'm thinking expand left and right with the left and right arrows and move backwards and forwards in time with up and down.

Is this possible without massive effort? I think it would increase speed of coding by a factor of two or more.

**Comment by isolver** [comment]
I think this falls into the area of the segmenting process 'acceleration
functionality' that we were talking about at our meeting. It is probably
the top one I also felt would be needed when I was playing around with the
current app prior to our meeting.

If you still agree, this type of functionality will be deferred until all
the must have 'core' requirements have been implemented. Then we can see
how we are doing for time and go from there.

Still very good to get these type of enhancements into the issue tracker so
we have the best overview of where the app functionality needs to go; both
within remaining next 2 contracted weeks, or at a later date when I (or
someone else) has some time to put volunteer hours into the project outside
of any contracted time.

**Comment by Mark-Torrance** [comment]
Sure. As I say, I think this is probably pretty essential to make it usable (but less essential than the whole thing actually working, of course). If you don't have time within the next two weeks, maybe you could do enough towards this to estimate how straightforward it would be? Then we can think about finding additional (contracted) time later.

**Comment by isolver** [comment]
I agree 100% about its importance. I'm not saying it will not be done for the initial release, I do not know right now; just putting things in perspective.

**Comment by Mark-Torrance** [comment]
Sure. I understand.

**Comment by isolver** [comment]
I think I thought you meant moving around created segments here. But you meant moving & resizing the selected time region in the timeline view, right?

I added some things like this , but not these exact things. I think these should be added as P1 if my new understanding of what you wanted is correct.

**Comment by isolver** [comment]
I guess this is not incorporated into #58 or one of them? I'm closing it; if you disagree pls reopen. ;)
