### ISSUE TITLE
Replace tabs /within/ segment name with '#' char in output reports

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#25]
Maybe make the char that tab is replaced with user definable as a project setting?

**Comment by Mark-Torrance** [comment]
> Maybe make the char that tab is replaced with user definable as a project setting?

Nah. This is so unlikely to occur that I think we just say "if you're silly enough to use a tab in your tag, you get a #" and say that in the documentation. Keeping the options as clean and uncluttered as possible is good, I think.

**Comment by isolver** [comment]
done; will be in next app exe release. One of the default tag names has a tab char in it for testing.
