### ISSUE TITLE
New Segments need to be assigned a parent node based on time period logic. 

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#26]
Currently, when a new segment is added, it's parent is set to the currently selected node in the segment tree. This is not what is required and needs to be changed as follows:

Where:

S = New Segment in process of being created.
ST = existing segment tree that contains all existing segments.
P = Application selected parent of S in ST
### 1. P Selection Logic:

a. If ST contains >=1 segment that wraps the time period of S, P is set to the smallest segment that wraps the time period of S.
b. Else, P is set to the root of ST
### 2. S Creation Error Rule:

Application should not allow S to be created if S has partial overlap with any of its siblings (i.e any existing children of P). In this case an error dialog should be displayed instead of the Create Segment Dialog.

Idea: Instead of showing an error dialog, why not just disable the "Create Segment" action (i.e. grey out menu item, toolbar item, ect.) so the user can not even try to create a new segment when this error situation exists. This seems more elegant than showing an error dialog when we already know an action should not be allowed based on the current selected data. @Mark-Torrance what do you think of this?

**Comment by Mark-Torrance** [comment]
> Idea: Instead of showing an error dialog, why not just disable the "Create Segment" action (i.e. grey out menu item, toolbar item, ect.) so the user can not even try to create a new segment when this error situation exists. This seems more elegant than showing an error dialog when we already know an action should not be allowed based on the current selected data. @Mark-Torrance what do you think of this?

Greying out is better than an error message. Even better, though, is to either (a) show the proposed segement (the region selected in the timeline) in red in the spatial view if it is illegal, changing to blue when it becomes legal or (b) in spatial view all existing children of currently selected segment in a different colour (greyed maybe) in the spatial view. This will serve both the reduce chances of overlap and show user what still needs to be tagged at that level for that segment.

Best would be all three (a, b, and greyed out menu).

**Comment by isolver** [comment]
I have now implemented rule based segment validation and hierarchy parent selection. Instead of showing an error dialog if the user tries to create a segment when the selection time range is 'invalid', several preemptive indicators of potential segment validity have been suggested:
1.  [x] only enable "Add Segment" action when time period is valid
2.  [  ] show the proposed segment (the region selected in the timeline) in red in the spatial view if it is illegal, changing to blue when it becomes legal 
3.  [  ] in spatial view all existing children of currently selected segment in a different colour (greyed maybe) in the spatial view. 
4. is done.
5. I think this a good idea, only adds information without adding any noise to the gui. Will add this before closing issue.
6. I'm not sure about this one. 
   - If implemented, It could be useful to apply it to both the timeline view and spatial view. 
   - It may add more noise than it does information.
   - Regardless, I do not think this is related to the current issue # here and should be moved to a new issue if it should be tracked for potential implementation. @Mark-Torrance what do you think about this?

**Comment by Mark-Torrance** [comment]
> > [ ] in spatial view all existing children of currently selected segment in a different colour (greyed maybe) in the spatial view. 
> 
> I'm not sure about this one. If implemented, It could be useful to apply it to both the timeline view and spatial view. It may add more noise than it does information. Regardless, I do not think this is related to the current issue # here and should be moved to a new issue if it should be tracked for potential implementation. @Mark-Torrance what do you think about this?

I'm can imagine that it might be useful, but better to add if users say they need it rather than pre-emptively. Opened as new issue and place on hold.

**Comment by isolver** [comment]
Implemented:

"show the proposed segment (the region selected in the timeline) in red in the spatial view if it is illegal, changing to blue when it becomes legal"

Closing this issue as 3rd option of "in spatial view all existing children of currently selected segment in a different colour" was moved out to separate issue by @Mark-Torrance
