### ISSUE TITLE
create by-segment reports infrastructure and output basic report

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#30]
- specify what variables need to appear in the report here (Mark todo)
- decide interface for creating these

**Comment by Mark-Torrance** [comment]
I'm just creating this now, and will fill it out spec later. I've thought through what is needed but need some space to write it out properly.

**Comment by Mark-Torrance** [comment]
By-segment reports have one row for each segment at a level (specified by user when selecting report). User should be able to initiate report generation from within the GUI and specify (by number) what level they want the report for.

Columns need to be as follows:

First "sub milestone"
Filename (as for by-sample report)
Trial (in future - as for by-sample report)
Segment category (currently same as file - as for by-sample report)
Segment parent tags (if any, excluding category, concatenated and separated with | which we can tell users is reserved).
Segment onset time
Segment duration

Second "sub milestone"
Time between segment onset and immediately previous sample with pressure > 0

If we can achieve both of these for the first release, plus some commenting of the code. I think it should be possible for me (and other informed users) to add more variables to these reports as research questions demand. I don't think it's a good idea to try and make them too sophisticated now.

I've separated into two groups because I'm guess that the first can just be read off the array, but that the second is a bit more complicated (searching back over previous items). I am comfortable doing this over lists (or course) but have never used a numpy array, so an example would set me in the right direction. However, I'm aware that time is running out, so the first "sub milestone" implemented in such a way that the code is extensible (is that the right word) is the priority.

@isolver does this sound feesible / sensible in available time.

**Comment by isolver** [comment]
I think this is doable. 

For the segment level report, Maybe instead of having the user select the level to output for, the report could:
- output a row for every segment in the tree, starting with level 1 segments, working its way down each level to level N.
- add a column indicating segment's level
- user can easily filter out rows in whatever SW they use to read / process the report

What do u think?

In terms of creating new report types, I've made the report exporting code with the idea of adding new report types by subclassing a base report class and overriding 4 methods in the new report class type. I'll comment that part of the code well and you can take a look and let me know what you think.

**Comment by isolver** [comment]
This is done I think. I modified the format a bit, adding some extra columns. Let me know if any should be removed or added. Will send updated exe friday.

**Comment by isolver** [comment]
Here are the current segment level report columns:

```
    * file: name of imported pen sample data file
    * seg_id: unique identifier assigned to segment.
    * category: The name of segment tree root the segment is part of
    * level: Segment level in the segmentation tree.
    * segpath: tree branch path to segment, not including current segment 
    * name: Name / tag assigned to the segment
    * start_time: Start time of the segment, in sec.msec format.
    * end_time: End time of the segment, in sec.msec format.
    * duration: end_time - start_time
    * start_index: The index of the segments first pen sample point 
                   in the full sample array ( 0 based indexing)
    * end_index:   The index of the segments last pen sample point 
                   in the full sample array ( 0 based indexing)
    * sample_count: Number of pen data samples that make up the segment
    * subsegment_count: Number of direct children of the segment.
    * prev_penpress_time: The first pen data point prior to the start 
                          of the segment, that has a pressure value > 0
    * next_penpress_time: The first pen data point following to the end 
                          of the segment, that has a pressure value > 0
```

**Comment by Mark-Torrance** [comment]
This looks great. Rather than look at an exe what I really need to do is look at and run the code, I think. I have numpy and pyqt4. What do I do? Do I make a pull request?

**Comment by isolver** [comment]
If you have pyqt 4.10 and numpy 1.9, then you just need to download and
install pyqtgraph.
- pyqtgraph  http://www.pyqtgraph.org/(I'm using latest source from
  project github repo https://github.com/pyqtgraph/pyqtgraph) Download
  the source and unzip somewhere on your pc.
- open a command prompt window and cd to the pyqtgraph foldeer that has
  the setup.py file in it.
- then type "python stup.py install" and press enter.

Then you need to get the MarkWrite source:
- In your web browser, goto MarkWrite
  https://github.com/isolver/MarkWriterepo.
- On the main page you will see a "Download zip" button on the bottom
  right hand side of the page. Download the Source.
- Open the downloaded file and copy the MarkWrite\markwrite folder to
  your python site-packages. Just copy the inner lower case 'markwrite'
  folder, not the top level folder in the zip.

To run the app, open the markwrite/runapp.py file in your python IDE and
launch it, or cd to the directoryt where that python file is and type "
python runapp.py

**Comment by Mark-Torrance** [comment]
I have pyqt 4.11.3 but older numpy. I’ll sort this out.

I’m going to need to play with this, and no doubt get some help from you, so I can work out how I can add to the by-segment report and then test it without having to run the app. My Python experience is limited entirely to programs of the form “read data file, do some stuff to data, output new data file” so I’m a bit at sea here. I do need to master this, though.

Mark

**Comment by isolver** [comment]
The way a report is created should not be too bad. I have abstracted away
all the file stuff, and you basically just define three main things when
creating a subclass of the base report type.
1. a list a strings, where each string is the name for one of the columns.
2. the number of rows that the report will output
3. the data for each row you want to output, simply as a list of values,
   where len(values) == len(columns)

So to add a column to a report you just add the column name in the list of
names, placed where you want it in the list, and then add a corresponding
value to the rowdata list that is returned for each row, with the new value
placed in the same index of the rowdata list as where you inserted the new
column name list.

**Comment by isolver** [comment]
can we close this issue and just open new ones for any extras wanted, unless there are bugs with what is currently implemented. Trying to clean up the issue list so I can get a clear sense of where I am at....
