### ISSUE TITLE
Does not recognise return to parent when adding new segment

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#31]
Behaviour: 
Create level 1 segment (Sent2 in example).
Double Click on level 1 segment in markup tree. Selects and zooms in correctly.
Create child of level 1 segment ("like" in example).
Double click on this child. Selects and zooms correctly.
Double click on level 1 segment (Sent 2). Selects and zooms correctly.
Select the child again. Desired behaviour: create segment is greyed out. Actual behaviour: create segment not greyed out and new segment created as child of previous child (i.e. at level 3).
Repeating this creates level 4 child etc. Output file is correct.

See screenshot...

![clipboard01](https://cloud.githubusercontent.com/assets/3226576/7122632/b1f53e06-e214-11e4-98c0-f204ebf853fd.png)

**Comment by isolver** [comment]
I noticed this before too but did not fix it or raise issue so it left my
head

Basically, a seg S can be created as a child of seg P that covers the full
time period as P, i.e S time period can == P time period.

I guess S should have at least one less data point then P to be valid
/ created?

**Comment by Mark-Torrance** [comment]
> I guess S should have at least one less data point then P to be valid / created?

YES.

**Comment by isolver** [comment]
fixed.
