### ISSUE TITLE
Double click timeline view's selected data region to zoom into the selected time period.

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#35]
Same idea as when a segment is double clicked in the segment tree, but this would allow zooming to the currently selected time period of the timeline view (the blue filled area) without needing a segment to do it. I find myself doing this expecting it to zoom, so it seems like a natural usability feature.

**Comment by Mark-Torrance** [comment]
YES

**Comment by isolver** [comment]
Implemented. Was easy to do when I was changing the selected region backend code.
