### ISSUE TITLE
Is the "Selected Data" view really needed?

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#37]
I'm starting to wonder if the Spatial View provides all the needed info that the Selected Data view provides. Since you can zoom into the selected data in the Spatial View if you want, in which case it is completely redundant with the Selected Data View.

Should we remove the Selected data view dock from the application?

Pros:
- frees up gui space, making Spatial View even more useful in some cases since a larger amount of data can be viewed at a higher zoom.
- reduces cpu effort ( amount unknown ) whenever selected data changes

Cons:
- None I can see

**Comment by Mark-Torrance** [comment]
No. I think it's important. It allows very precise control over exactly what is selected, and also, crucially, allows you to "play forward" through the selection so you can see the order in which strokes within a selection are made. Not so important if just choosing words - though still nice as a double check - much more important if interested in letters or strokes. I know that you can also do this with the spatial view, but being able to zoom out the spatial view (for orientation) but still have very fine control - down to the sample level - of the selection is a major bonus, I think.

**Comment by Mark-Torrance** [comment]
The no means no I disagree. i.e. yes, it's needed.

**Comment by isolver** [comment]
OK, not sure I 100% agree, but I trust your stance on this. Hey, it is already there so it is easy to just leave. ;)

After some more use of the app, if you start to see my POV, and if it for some reason makes a significant difference to performance, it can be considered for removal. ;)

**Comment by Mark-Torrance** [comment]
Sure.
