### ISSUE TITLE
MUST HAVE

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#38]
#19 will be essential when we have data with zero pressure samples, but of no use now.
#16 is useful now but unless it is quick to implement we can do without it

Assuming the tool is going to be used in earnest over the next couple of months...
#12 is quick (I assume) and therefore should be done
#24 is important, I think
#30 (which requires more input from me first) is something that I will have to do outwith the program if it is not done within it, so makes sense to do now. Ideally in a way that allows me to teak the code later.

**Comment by isolver** [comment]
I've taken this information and created two milestones for the project. 
1. First Release: tracks progress of issues that must be implemented before mark will consider the application to be in an acceptable state (but maybe not 'ideal')  functionality and stability wise for project delivery.  
2. Future Release: issues to do at some unspecified future date.

Each project issue is assigned to one of the two milestones. The issues @Mark-Torrance lists in the OP have all been assigned to the First Release Milestone.

So I think we can then close this issue if the above makes sense to you @Mark-Torrance .

**Comment by Mark-Torrance** [comment]
This makes sense definitely. But there are several things in the first milestone that I would like to change priorities for, and one or two need to move to second milestone. Shall I just do that? @isolver

**Comment by isolver** [comment]
SOrry, just saw this now. Yes, please change milestones and priorities as
you see fit. I'm taking a break for a bit, so let me know when you have
updated the issue milestones and tags as desired and I will then review the
status of things and get back at it. ;)

Thanks,

**Comment by isolver** [comment]
Can we close this one as well now?
