### ISSUE TITLE
Create initial output report as defined in google doc

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#4]
See example format here: https://docs.google.com/spreadsheets/d/1sAc3CP1L5BJNlDCToPnUcuVtVg0GyMeB3WMzkHVxB1w/edit?usp=sharing

**Comment by Mark-Torrance** [comment]
Made minor changes to google doc (added filename and trial column - for future use) and removed these from the tag hierarchy.

**Comment by Mark-Torrance** [comment]
Also: Tab delimited, and leave empty cells blank (don't indicate missing codes with "." or similar)

**Comment by isolver** [comment]
Added 'index' column to report, which is the index of the sample within the original data sample array.

**Comment by isolver** [comment]
If a segment name / tag has a tab char ('\t') /within/ its text, I guess it should be replaced with a space, or 4 spaces? Otherwise the report will get messed up. 

Another option would be to put "" around data in string columns of the report.

@Mark-Torrance What do you think we should do here?

**Comment by Mark-Torrance** [comment]
Yes. I can't imagine people using tab within a segment name, but remove and replace with '#'  or similar (better than space(s) because these will potentially get interpreted as word boundaries in post-processing of data). Not strings in quotes, I think. Creates more problems that it solves in my experience.

**Comment by isolver** [comment]
Create issue #25 to track this specific requirement

**Comment by isolver** [comment]
This is now completed other than adding the values for the 'trial' and 'file' columns. 
The category and level columns are working as I understand them too, so it would be good if you can confirm that the output is what you were expecting.

**Comment by isolver** [comment]
@Mark-Torrance 
1. What should I use for the trial column of the report?
2. Should the file column be the project file path or the original pen point data path?

Thanks!

**Comment by Mark-Torrance** [comment]
1. Leave blank (actually, omit for now).
2. Just the stem of the filename? So S66.xml and S66.txyp both -> S66. Not full path, I think.

**Comment by isolver** [comment]
1. Removed from report
2. So this would be equal to the CAT1 column then, so should we remove the filename field as well?
   Thanks.

**Comment by isolver** [comment]
Completed.

For file column, I do as you suggested and use the project input file name without extension
