### ISSUE TITLE
Create segment action state does not always work.

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#40]
1. Cases where I have seen the create segment action enabled when it should have been disabled:
- Right after you create a new segment. The create button stays active. If you go to another segment and then back to the first segment, it is disabled as expected.
1. Cases where create segment was disabled but should have been active:
- Right after you delete a segment the create action stays disabled. As soon as you move the selection region it goes to the right state.

When the create segment action state is invalid, you will also see the coloring of the selected data in the Spatial view is also the wrong color. This is expected as the two are driven by the exact same return value.

**Comment by Mark-Torrance** [comment]
This...

> Cases where I have seen the create segment action enabled when it should have been disabled: right after you create a new segment. 
> 
> The create button stays active. If you go to another segment and then back to the first segment, it is disabled as expected.

is resolved by as a useful byproduct of #43?

**Comment by Mark-Torrance** [comment]
Oh, and this...

> Cases where create segment was disabled but should have been active:
> Right after you delete a segment the create action stays disabled. As soon as you move the selection region it goes to the right state.

...will be resolved by solving #42?

**Comment by isolver** [comment]
Fixed
