### ISSUE TITLE
Move selection one sample on after tagging

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#43]
When tagging lots of sequential segments with zero-pressure gaps in between (words in a sentence, typically) the easiest way to choose the next word is to take the leftmost boundary of the selection, leapfrog it over the other boundary, and position it at the end of the next word. This is a smooth and effective way of choosing next segment _except_ that it overlap with the previous segment by one sample (because the now leftmost boundary is at the last sample in the previous word. So a second mouse action is required to nudge the selection forward slightly. Because markup in this way (choosing sequential segments) will be by far the most common way of marking up, this second action could be avoided by:

When exiting tagging dialogue (not on cancel), move selection forward one sample. 

There are some minor unwanted consequences of this, but as a quick fix (if it is) the benefits substantially outweigh these.

Could be toggled with a system option at some point in future, but should be default behaviour for now.

@isolver: what do you think? If yes, reduce priority if not a quick change.

**Comment by isolver** [comment]
I 100% agree with this and also though this would be nice when created word level segs, and then also when creating letter level segs.

Once Q: You say:

> the easiest way to choose the next word is to take the leftmost 
> boundary of the selection, leapfrog it over the other boundary, 
> and position it at the end of the next word.

I take the " leapfrog it over the other boundary," part to mean move the selection region ahead one sample.  

But what about the "and position it at the end of the next word." part? How do you think the app could best decide what the likely position of the 'end' of the next work is so it knows where to set the selection region end position?

**Comment by Mark-Torrance** [comment]
> I take the " leapfrog it over the other boundary," part to mean move the selection region ahead one sample.
> 
> But what about the "and position it at the end of the next word." part? How do you think the app could best decide what the likely position of the 'end' of the next work is so it knows where to set the selection region end position?

I'm just describing my actions as user here, not anything that needs changing in the program. The "nudge forward one sample" just facilitates what I want to do.

What I actually mean is this.

![clipboard01](https://cloud.githubusercontent.com/assets/3226576/7182368/c0342ffa-e448-11e4-9709-0674e0be3ec0.png)

The front boundary is going to be correct for the next segment (except it needs moving forward one sample) so it's quickest to move the back one so that it become the front boundary of the next segment (and so forth and so on).

**Comment by isolver** [comment]
On Thu, Apr 16, 2015 at 9:58 AM, Mark-Torrance notifications@github.com
wrote:

> move the back one so that it become the front boundary of the next segment
> (and so forth and so on).

I think we are saying the same thing, using different terms, based on your
picture if
- 'front boundary' == 'selection region end time'
-  'back boundary' is selection region start time.

Is this correct? If so, the Q remains how to determine the selection
regions end time for the jump (time period that the red line / arrow you
drew on the graph should be). Do you mean just make it so that the
selection region does not change in duration, and we make it's start time
equal to last created segments end time + one sample? Or do you see there
being some more intelligent heuristic that could be used on the data to
decide where the regions

**Comment by Mark-Torrance** [comment]
> - 'front boundary' == 'selection region end time' - 'back boundary' is selection region start time. Is this correct?

YES.

> If so, the Q remains how to determine the selection regions end time for the jump (time period that the red line / arrow you drew on the graph should be). Do you mean just make it so that the selection region does not change in duration, and we make it's start time equal to last created segments end time + one sample? Or do you see there being some more intelligent heuristic that could be used on the data to decide where the regions

Ah, I see the issue. I keep forgetting the sample != fixed time period.

> Do you mean just make it so that the selection region does not change in duration, and we make it's start time equal to last created segments end time + one sample?

YES. This isn't exactly what I meant, but actually is the best way to do it. It allows the same thing as I was achieving with my leapfrogging, but without leapfrogging.

**Comment by Mark-Torrance** [comment]
I suggest making this the default (only) behaviour for now, but add turning it off at system level as a wish for future release.

**Comment by isolver** [comment]
OK, understood.

**Comment by Mark-Torrance** [comment]
I think this is now superseded by #46. @isolver close?

**Comment by Mark-Torrance** [comment]
Sorry, ignore that. This is still needed.

**Comment by isolver** [comment]
Implemented, but by user pressing Ctrl+Right Arrow key if a current segment is selected.

**Comment by Mark-Torrance** [comment]
Excellent. For the future: add as an event that occurs whenever the segment tag dialogue is closed?

**Comment by isolver** [comment]
Give the current code a try and then let me know. If we do make it automatic when segment is created, it should be able to be disabled in settings IMO.

Also, besides the shortcut key, there is a toolbar button that also does it.Looks like a  >| button

**Comment by Mark-Torrance** [comment]
I’ll try. Having both mouse and key actions available sounds good.

**Comment by isolver** [comment]
TODO:
- [x] Agreed that the same auto trim logic that is applied on segment creation (pre dialog display) should be applied to the start and end times of the shifted time period here, prior to the time period region being updated in the gui

**Comment by isolver** [comment]
Done. Actual can be used regardless of if the selected time period is a segment or not.
