### ISSUE TITLE
Priority Code commenting / doc strings

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#47]
As a priority, the following areas of code should be well commented:
1. The numpy recarray that holds the pen sample data loaded when the project started (app.project.pendata)
2. The internal segment tree structure (app.project.segmentset object, markwrite.segment.py module)
3. The markwrite.reports module, with a focus on explaining how to create a new report type, or edit an existing report. When creating a report, understanding items 1. and 2. are very helpful. ;)

**Comment by Mark-Torrance** [comment]
Thanks Sol.

**Comment by isolver** [comment]
Add commenting to markwrite.reports.**init**.py that should get anyone going on creating a report type.

I also added code so that custom report classes  saved in a customreports.py file are dynamically imported when the application starts, and each custom report results in a menu item being created in the file->Export menu of the app for that report..

The example report in the docs, 'RawSampleDataReportExporter', has been added to the customreports.py file so it is loaded as a new report type now.

**Comment by Mark-Torrance** [comment]
Thanks. Should be really helpful. I'll have a look when I get a chance.

**Comment by isolver** [comment]
I'm uploading the latest exe folder and will send you a link when it is
done.
