### ISSUE TITLE
Add support for segment heirarchy

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#5]
- [x] When a user creates a new segment, it should be added as a child of an existing segment that has a time period spanning the new segment.
- [x] enforce rule that children of a parent segment all fall within the parent segments start <-> end time period.
- [x] enforce rule that sibling segments can not have overlapping time ranges
- [x] If Segment is deleted, all child segments must also be deleted.

**Comment by isolver** [comment]
@Mark-Torrance : When we discussed adding the segment hierarchy stuff, I think the agreement was that when a new segment was created, if another segment was selected in the segment tree, the new segment would become a child of the currently selected segment.  

Since we need to add a rule that a child segment must fall within the time period of it's parent segment, then this suggests the above logic will not work well. Where in the segment tree a new segment is added should not depend on what node of the tree is selected, as it could very well violate this rule. 

Instead I think the following makes sense for determining where a new segment should be placed in the segment tree:
1. check existing segments for any where their time period surrounds the new segment time period.
2. If none are found, then the segment gets added to the top level (as is the current functionality)
3a. If 1 existing segment is found where it's time period 'wraps'  the new segments time period, then the new segment is added to the existing segment found.
3b. If >1 existing segment is found where it's time period 'wraps'  the new segments time period, then the existing segment with the smallest time period duration is used as the parent for the new segment.  

Do you agree?

**Comment by Mark-Torrance** [comment]
I think that this can be done more simply. It's late, though, and so I might be missing something. I want to respond now though rather than leave it until Monday.

The way I'm thinking about this is driven by the necessity to output tags in the format here: https://docs.google.com/spreadsheets/d/1sAc3CP1L5BJNlDCToPnUcuVtVg0GyMeB3WMzkHVxB1w/edit?usp=sharing which requires:

a. that segments at a particular level do not temporally overlap. i.e. they are across discrete, adjacent sets of samples. I think this is the key point.
b. that segments at level n+1 are nested within segments at level n. Meaning that that no level n+1 segment crosses a level n segment boundary.

We need to enforce this in how segments are tagged. So it becomes impossible when choosing segments of the timeline to violate these rules. I think this can be done by (a) prohibiting segments that exist at the same level from overlapping and (b) requiring that segments at level n+1 never cross a level n boundary. I think might be achieved as follows: 
1. At level n, attempting to assign a tag to a sample that is already tagged at level n raises an error.
2. Users are encouraged not to attempt creating overlapping segments by changing colour of tagged (at current level) segments in all three views. So they don't try and tag samples that are already tagged.
3. "Current level" is determined by the segment that is currently selected in the Tagging Tree view (is that what we decided it was called? the tree in top left window). So if a segment category is selected, or if we don't implement multiple hierarchies then we are coding at root level, then coding level is 1. If a level 1 segment is selected then coding level is automatically level 2.
4. Once one or more segments have been been tagged at Level 1, then selecting one of the tags (a word for example) in the Tagging Tree results in display of just that segment in the Timeline and Spatial views. i.e. we are no longer seeing data for the whole file but just for that segment. This can then be segmented and tagged, creating Level 2 segments. There is, therefore, no possibility of non-nested level 2 tags. Rule 1 still applies to these new segments.

I think this also handles the "zoom on selection" issue. Rather than zooming, selecting a tag just redraws temporal and spatial views across just those segments coded by the tag. No need to zoom.

Does this sort of thing work for you? It seems simpler, both in use and from a programming point of view (as I understand things, which may well be wrong) than what you are suggesting.

**Comment by isolver** [comment]
I think this could work, but does it not reduce to the same as what I
suggested, except that the time overlap rule is used to give errors if the
incorrect tag tree node is selected, instead of being used to have the
program intelligently use the rule to determine a tags parent?

I think from a user POV, the second option is 'simplier'.

I have not had a coffee yet, so maybe I am missing a key difference.

Other considerations:
- the auto zoom / limit data bounds on segment tree node select
  functionality should be a mode that is easily enabled / disabled, as per
  current requirement definition. I think it is very likely people will want
  to be able to step through segments while seeing the overall data, or at
  least a large set of data than just the parent segments time period. I.e
  when 'browsing' through existing tags.
- Either way segments are added to the right level in a
  categories segment tree, this rule means that the order a user created
  segments is very important. For example, to the if a user goes through and
  creates all letter level segments, the can not then create word level
  segments. The user must know to create word level segments first. This may
  be a potential usability issue ?? If so, we need to live with it or refine
  the requirements to specify how to handle it.

Thank Mark.

**Comment by isolver** [comment]
BTW, figuring this detail out is not stopping me from getting the levelled
segments functionality implemented in general, where the time period
overlap rule is ignored for now.

When we get these details ironed out, then the time period overlap rule can
be added.

**Comment by Mark-Torrance** [comment]
I'm sorry, I should have read and thought through your rules more carefully before responding. Post beer, late night program-speccing is probably sub-optimal.

Your rules intelligently choose a segment level, but they don't (I think) prevent partially overlapping segments. So imagine just two segments: S1 spans samples t to tt. S2 spans samples t+n to tt+nn (where n and nn are > 0). This S1, S2 combination must be illegal within one hierarchy (and we are only implementing one hierarchy of the foreseeable future). 

So we have to tell users that they are attempting an illegal segment. 

So, I think, your rules need modifying as follows:

For proposed segment S:

Segment W = the smallest segment that wraps the time period of S. If no tagged segment exists that wraps S then W = top level of hierarchy (i.e. the "whole file" segment).

If S has partial overlap with any child of W then raise error (where child == segment one level below level of W - so ignore grandchildren etc).
Else make S child of W.

There's a serious usability issue here, though. It will be very easy to intend to create an S that is wrapped by a specific W (say the final letter in a word) but to accidentally create partial overlap: e.g., you intend to create a sub segment that ends at tt but accidentally select tt+1, for example. This will raise an error, so no damage done, but we ought to try and avoid this happening. The "change colour" suggestion that I made earlier is redundant now, I think (or at least doesn't make sense). However giving users the option of only having W available for markup is important. 

You're absolutely right about keeping existing bahaviour such that clicking on a segment tag just highlights this in the temporal and spatial views and brings it up in the segment view. This is essential. 

So how about 
single click on segment tag -> existing behaviour
double click on segment tag -> make only that segment available for coding.

I think this (intelligent hierarchy allocation plus user handholding) will make the tool really simple and intuitive.

That, by the way, was a two coffee and very patient wife response! Going out in the sunshine now.

**Comment by isolver** [comment]
On Sat, Apr 11, 2015 at 10:51 AM, Mark-Torrance notifications@github.com
wrote:

> S1 spans samples t to tt. S2 spans samples t+n to tt+nn (where n and nn
> are > 0). This S1, S2 combination must be illegal within one hierarchy (and
> we are only implementing one hierarchy of the foreseeable future).

Good point. In this case there is nothing to do but give an error. I guess
we could show a dialog that gives the user 2 options:
1. cancel the segment creation
2. have the software trim the new segment so that it fits within
   the candidate parent segment (new segments start or end time is already
   within the candidate parent segments time period.)

I think we can start with 1. and add 2. when it bubbles up to a priority 1
requirement. What do you think?

So how about

> single click on segment tag -> existing behaviour
> double click on segment tag -> make only that segment available for coding.

Currently double clicking a segment brings up the segment name editing
dialog, allowing a user to rename a segment after it was created. I think
your double click idea is probably a better use for the double click
though, so we should change it to that. What then should allow a user to
edit the name / tag of a segment? Ideas:
1. Do not allow user to change a segment name once it is created
2. Add a right click on a segment node bringing up a popup menu that
   allows user to select (at minimum) the edit name dialog.

Again, I think we can start with 1. and add 2. when it bubbles up to a
priority 1 requirement. What do you think?

That, by the way, was a two coffee and very patient wife response!

Amazing what coffee, and a patient wife, can do for a guy. ;) I'm the same
way. ;)

**Comment by isolver** [comment]
Sorry, I do not think I got your stance on this potential issue with the
current plan:

Either way segments are added to the right level in a categories segment

> tree, this rule means that the order a user created segments is very
> important. For example, to the if a user goes through and creates all
> letter level segments, the can not then create word level segments. The
> user must know to create word level segments first. This may be a potential
> usability issue ?? If so, we need to live with it or refine the
> requirements to specify how to handle it.

What do you think?

**Comment by Mark-Torrance** [comment]
> S1 spans samples t to tt. S2 spans samples t+n to tt+nn (where n and nn
> are > 0). This S1, S2 combination must be illegal within one hierarchy (and
> we are only implementing one hierarchy of the foreseeable future).
> 
> Good point. In this case there is nothing to do but give an error. I guess
> we could show a dialog that gives the user 2 options:
> 1. cancel the segment creation
> 2. have the software trim the new segment so that it fits within
>    the candidate parent segment (new segments start or end time is already
>    within the candidate parent segments time period.)
> 
> I think we can start with 1. and add 2. when it bubbles up to a priority 1
> requirement. What do you think?

YES – though the importance of 2 will substantially reduce if we implement this: double click on segment tag -> make only that segment available for coding.

> So how about
> 
> > single click on segment tag -> existing behaviour
> > double click on segment tag -> make only that segment available for coding.
> 
> Currently double clicking a segment brings up the segment name editing
> dialog, allowing a user to rename a segment after it was created. I think
> your double click idea is probably a better use for the double click
> though, so we should change it to that. What then should allow a user to
> edit the name / tag of a segment? Ideas:
> 1. Do not allow user to change a segment name once it is created
> 2. Add a right click on a segment node bringing up a popup menu that
>    allows user to select (at minimum) the edit name dialog.
> 
> Again, I think we can start with 1. and add 2. when it bubbles up to a
> priority 1 requirement. What do you think?

Can you move the current double click behaviour (bring up editing dialogue) to right click, without implementing a right click menu?

So we have…

single click on segment tag -> show segment in all views (existing behaviour)
double click on segment tag -> make only that segment available for coding.
Right click on segment tag -> show segment in all views plus bring up editing dialogue.

I think this is an intuitive action allocation for Windows users. Double click “opens” the segment. Right click gives access to rename.

Then we can add a right click “context” menu later if it becomes necessary.

**Comment by Mark-Torrance** [comment]
I don’t think I get my stance on that either. When did I say that? Anyway, it’s now out of date. I think the solution that we’ve worked through here is neat.

**Comment by Mark-Torrance** [comment]
Ah, sorry, misunderstood. Try again:

**Comment by Mark-Torrance** [comment]
Try again...

> Either way segments are added to the right level in a categories segment tree, this rule means that the order a user created segments is very important. For example, to the if a user goes through and creates all letter level segments, the can not then create word level segments. The user must know to create word level segments first. This may be a potential usability issue ?? If so, we need to live with it or refine the requirements to specify how to handle it.
> What do you think?

I understand what you are saying. Put another way, what if a proposed segment S completely wraps one or more existing segments. I think just raise an error, and tell users not to do it. This reduces flexibility, but not in a way that really inconveniences users.

**Comment by Mark-Torrance** [comment]
Elaborating on my thinking for "This reduces flexibility, but not in a way that really inconveniences users." (you can ignore this, but I want to make a note for future reference).

There are two different cases where S might completely wrap one or more existing segments:
1. It might exactly wrap several segments (letters coded first and then words). In this case, this doesn't need to be done by the tool. There is no new segmenting to be done. All the information is already there. So this is more easily done automatically on the output file (and it's not our responsibility for supporting this).
2. The new segment wraps one or more existing segments, plus some additional untagged samples.This would be a rather chaotic and unsystematic approach to markup. We need to save users from themselves. If and when we implement multiple parallel hierarchies, if a user wants to suddenly start creating superordinate segments then they can do this in a new hierarchy. If we then add the possibility of copying tags from existing hierarchies to the new one, then this would also save the user duplicating actions. However, this level of sophistication is way beyond what I think 90% of users are going to need.

**Comment by isolver** [comment]
OK, base segment hierarchy support added. /None/ of the rules, intelligent parent selection, invalid segment creation state conditions, changing of double click node behavior has been implemented. Currently, whatever node in tree is selected is what is used as parent node.

I see all the other requirements that have come out of this discussion as separate enhancements to this base logic, so I'm closing this issue and will create several new issues that cover all the different sub requirements that have been defined in the comments of this issue. If I miss anything let me know (give me until Monday AM EST to get all the new issues entered).

**Comment by isolver** [comment]
I guess there are only 2 new enhancement issues that need to be created as follow up on this issue. I have created them, #27 and #28
