### ISSUE TITLE
Opening new file during an existing session...

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#55]
Opening new input (txyp, xml) file during an existing session is possible but spatial view does not (always) automatically update to new data and timeline just displays y data.

None of this is a problem really. Why would you want to open a new file before you've finished coding an old one? Thought I'd better flag for a future more public release, though.

**Comment by isolver** [comment]
> Why would you want to open a new file before you've finished coding an old one?

You would not, but you still would not want to have to close the app and restart it just to start working on the next file.

I will fix this bug this week, should just be noted to them for now.

Am creating exe version of latest code. Will send download link once it is on googledrive

**Comment by Mark-Torrance** [comment]
Excellent. Thanks.

Mark

**Comment by isolver** [comment]
fixed
