### ISSUE TITLE
ctrl+up and down arrow actions should move selection finish to sample before next zero pressure sample

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#58]
Currently jumping the selected-segment end time using ctrl+ up or down arrows moves the end time to the next or previous zero pressure sample. So the zero pressure sample is included in the segment. This potentially creates illegal selections (because the parent excludes the zero-pressure sample).

**Comment by isolver** [comment]
Fixed. 

As a side effect, when a selection is expanded to the right, if the initially calculated end time falls between sample data point times, the end time to truncated to the last sample. Where the last sample is 0 pressure or not depends on the app settings as normal.
