### ISSUE TITLE
Rewise segmentation quick keys

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#59]
This is a combination of just (re)assigning actions to keys, and adding one new action:

(right, left refer to cursor keys, ips = inking pen sample = non-zero pressure sample)

I'm assuming that actions can be assigned to the arrow keys without a modifier, but if not, the use alt, perhaps.
- ctrl+right: move whole selection so that start is at first ips after current end, duration unchanged (current behaviour)
- ctrl+left: same but backwards. Move whole selection so that end is at the first ips before current start, duration unchanged.(new action)
- right: move end of selection forward to the next ips following a zero pressure sample. (current ctrl+up behaviour, almost - see #58)
- left: move start of selection backward to the next ips following a zero pressure sample (current ctrl+down behaviour, after #58 fix)
- enter (or some other handy key): bring up tagging dialogue

**Comment by isolver** [comment]
> right: move end of selection forward to the next ips following a zero pressure sample. 
> (current ctrl+up behaviour, almost - see #58)

You mean this would be like current "ctrl+right + ctrl+up behaviour"  right, since you want the start time to be first sample of next ips, and end time last sample of ips. 

Same would go for the yet to be created new 'left' action, once ctrl+left is added?

**Comment by Mark-Torrance** [comment]
> > right: move end of selection forward to the next ips following a zero pressure sample.  (current ctrl+up behaviour, almost - see #58)
> 
> You mean this would be like current "ctrl+right + ctrl+up behaviour" right, since you want the start time to be first sample of next ips, and end time last sample of ips.
> 
> Same would go for the yet to be created new 'left' action, once ctrl+left is added?

No I mean that it is exactly current ctrl+up behaviour, now that #58 is fixed.

**Comment by isolver** [comment]
> No I mean that it is exactly current ctrl+up behaviour, now that #58 is fixed.

All that was changed to fix #58 is that if the new end selection time is between ips1 and ips2, it applies the trim operation to roll the end point /back/ to the first (non zero) ips1 sample time.

**Comment by Mark-Torrance** [comment]
re #58: ctrl-up / down necessarily moved the end to a sample though, I thought, because the action was to find the next zero pressure sample. I don't understand how it could land between them. The issue that I found was that new segment then included the zero pressure sample (thus creating segments that crossed the boundary of a parent) but should have excluded it.

I'm losing the plot a bit with this, though, so I'm going to step back and just say what I think does and does not currently work, and leave you to it. I think I'm just confusing things, otherwise.
- Assuming #58 is fixed, the ctrl+up and ctrl+down actions work really well. I just think they would be better if they were on the right and left keys.
- The action that jumps the whole segment forward produces some flakey behaviour, which I've tried to describe in #60.
- It would be cool to have backward jumps as well.
- It would be cool to have an quick key to bring up the tagging dialogue.

Overall, I think these key actions are brilliant - they make tagging much quicker - just could be brillanter with a few teaks.

**Comment by isolver** [comment]
I'm getting confused too. I'll take a step back and read your requests
again and implement what at least seems to make sense to me based on that.
You can then take it for a spin and let me know if it is /right/ or not.

Re using ENTER to create a segment, it does not work using the built in
action shortcut Qt functionality.i'll have to figure out how to get the app
to monitor key events and grab enter events under the appropriate
conditions, otherwise pass the event along to the app widgets.

**Comment by Mark-Torrance** [comment]
My benchmark test is: segment into sentences and tag, then segment sentences into words and tag. If the quick keys allow me to do this quickly, and without any mouse actions, then we’ve won. You could maybe just try this and fix anything that you think needs fixing.

Please don't spend ages, on any of this, but particular in getting ENTER to work. Any key will do. Just use what Qt already provides, I suggest.

**Comment by isolver** [comment]
@Mark-Torrance  Please review this summary and comment as soon as you can.

Here is my view on what a full, rounded, set of actions are that could be applied to changing the selected time period of the timeline view. There are actually 6 in total; 2 of which have not been discussed yet. Lets worry about shortcut key assignment after we get on the same page about what the action set should be. Let me know if you agree. I'll then implement based on feedback.

### General Definitions Used
- The currently selected time period is bounded by start and end times [CTs,CTe]. 
- The time period bounds after one of the actions is [NTs,NTe].
- IPS == inking pen sample == non-zero pressure sample
- A segment (SG) is a tagged time period with the time range [SGs,SGe], where
  - SGs and SGe must both equal the time of a pen sample timestamp
  - SGs < SGe.

### Selected Time Period Actions
1. _Moving Whole Time Period_
   a. _Forward_:  (currently implemented)
   - NTs = CTe+0.001
   - NTe = NTs + ( CTe-CTs)
   
   b. _Backward_: (new feature)
   - NTs = NTe -  CTe-CTs)
   - NTe = CTs - 0.001
2. _Changing End Time Only_ (rule NTs < NTe must be enforced)
   a. _Increase_ (currently implemented with bug fix #58)
   - NTs = CTs
   - NTe = First IPS time where (IPS time >  CTe) and (IPS could be a SGs) 
   
   b. _Decrease_ (currently implemented with bug fix #58)
   - NTs = CTs
   - NTe = First IPS time where (IPS time <  CTe) and (IPS could be a SGe)  
3. _Changing Start Time Only_  (rule NTs < NTe must be enforced)
   a. _Increase_ (new feature)
   - NTs =  First IPS time where (IPS time >  CTs) and (IPS could be a SGs) 
   - NTe =  CTe
   
   b. _Decrease_ (new feature)
   - NTs = First IPS time where (IPS time <  CTs) and (IPS could be a SGs) 
   - NTe =  CTe

**Comment by Mark-Torrance** [comment]
#Notes in text

OK, here is my view on what a full, rounded, set of actions are that could be applied to changing the selected time period of the timeline view. There are actually 6 in total; 2 of which have not been discussed yet. Lets worry about shortcut key assignment after we get on the same page about what the action set should be. Let me know if you agree. I'll then implement based on feedback.

General Definitions Used
-   The currently selected time period is bounded by start and end times [CTs,CTe].
-   The time period bounds after one of the actions is [NTs,NTe].
-   IPS == inking pen sample == non-zero pressure sample
-   A segment (SG) is a tagged time period with the time range [SGs,SGe], where
  -   SGs and SGe must both equal the time of a pen sample timestamp
  -   SGs < SGe.

Selected Time Period Actions
1. ```
    Moving Whole Time Period
   ```
   
   a. Forward: (currently implemented)
   -   NTs = CTe+0.001 #ok, but why not First IPS time where (IPS time > CTe) and (IPS could be a SGs)
   -   NTe = NTs + ( CTe-CTs)

b. Backward: (new feature) #yes

```
 *   NTs = NTe - CTe-CTs) #see comment above
 *   NTe = CTs - 0.001
```
1. ```
    Changing End Time Only (rule NTs < NTe must be enforced)
   ```
   
   a. Increase (currently implemented with bug fix #58https://github.com/isolver/MarkWrite/issues/58)
   -   NTs = CTs
   -   NTe = First IPS time where (IPS time > CTe) and (IPS could be a SGs)

b. Decrease (currently implemented with bug fix #58https://github.com/isolver/MarkWrite/issues/58)

```
 *   NTs = CTs
 *   NTe = First IPS time where (IPS time < CTe) and (IPS could be a SGe)
```

#I considered 3. I’m not convinced it’s actually necessary, given that we have the other two. However, if it’s easy to implement we could add it and then disable it it doesn’t prove useful or gets in the way.
1. ```
    Changing Start Time Only (rule NTs < NTe must be enforced)
   ```
   
   a. Increase (new feature)
   -   NTs = First IPS time where (IPS time > CTs) and (IPS could be a SGs)
   -   NTe = CTe

b. Decrease (new feature)

```
 *   NTs = First IPS time where (IPS time < CTs) and (IPS could be a SGs)
 *   NTe = CTe
```

**Comment by isolver** [comment]
@Mark-Torrance : 

> - NTs = CTe+0.001 #ok, but why not First IPS time where (IPS time > CTe) and (IPS could be a SGs) 

In general, I guess because the time period selection is not tied to discrete times from the sample data stream.

In detail It means that 

a. enforcing:

> NTe = NTs + ( CTe-CTs)

is not technically possible, since there will often not be a sample at time  NTs + ( CTe-CTs). 

b. of my (non actual researcher) thinking that someone may in theory want to create 'segments' for the gaps, or partial gaps, in time in the pen data sample stream.

If  NTs + ( CTe-CTs) should really mean  NTs + ( CTe-CTs) _rounded to the closest sample data point time_ and / or this is a totally silly idea then what you suggest could be done easily, it is just not how it is done now.

**Comment by Mark-Torrance** [comment]
> b. of my (non actual researcher) thinking that someone may in theory want to create 'segments' for the gaps, or partial gaps, in time in the pen data sample stream.

This is true, but it would be odd to actually mark up this way and to a certain extent we want to save researchers from doing silly things. The philosophy of the coding in the system as it stands is that you code samples and then look for non-inking periods prior to or within these. If researchers really want to start a segment at some arbitrary point when nothing was happening, then they can still do this with the mouse (and turn off the autotrim function, if/when we implement that as a setting).

For present purposes we are just implementing tools that will speed up coding in particular (very common) circumstances when segments are bounded by pen lifts (with bounding non-IPS's excluded). So I think it makes sense to always snap to an inking sample.

So, I suggest that all of these quick-key actions force start and ends at an IPS.

**Comment by isolver** [comment]
Ok, sounds good. Will always snap to a sample point when one of these
actions is done.

I think everything is very clear now; I know what to do.

I'll get this updated / added this evening.

Sol

**Comment by isolver** [comment]
OK, committed initial implementation for this. 

Current implementation notes:
- shortcut keys for time period change action have not been changed yet. New actions have no shortcut keys at all right now. I'll finish this part Thursday as well as do more testing.
- To create a new segment, the ENTER (RETURN) key should now work as the shortcut. Please let me know if it does not for you. Qt defines an 'Enter' and a 'Return' key; I had used 'Enter' before when I said it was not working. Switching it to use 'Return' now makes it work (even though on my keyboard the 'Return' key is labeled 'Enter' )   ;)

**Comment by Mark-Torrance** [comment]
Enter to create new segment tag works fine for me.

The jump forward (and back) still behaves badly for me, though. Two issues: 
1. there are points where nothing happens - I can't work out why that might be the case.
2. The selection slowly shrinks in size across multiple jumps. I can see why that happens. I think the following fixes it:

Moving Whole Time Period Forward:
NTs = First IPS time where (IPS time > CTe)
NTe = NTs + ( CTe-CTs)

So duration remains constant, NTs is always at an IPS, but NTe is not necessarily at an IPS. Users then perform actions to move Te to the IPS that represents the end of their desired segment.

You argument against this was 

> is not technically possible, since there will often not be a sample at time NTs + ( CTe-CTs).

I might be being slow here, but I don't see why. For /find first IPS time where (IPS time > CTe)/ 
to be doable, CTe does not have to be at a sample time?

As far as I can work out the action as defined above should always be possible except in cases where NTe > time of last sample in file. In which case do nothing and raise an error. Currently jumping beyond end of file results in the selection disappearing and is then difficult (though not impossible) to retrieve.
1. Changing End Time Only 
   The actions for moving just Te works perfectly, I think. It isn't actually implementing the following rule, though, is it?

> NTe = First IPS time where (IPS time > CTe) and (IPS could be a SGs)

This would just move by one sample at a time. What it's doing (correctly) is finding the next IPS that immediately precedes a nonIPS. So it's jumping to the last ink before a pen lift.

**Comment by isolver** [comment]
> The jump forward (and back) still behaves badly for me, though. Two issues:

Ya, I should have put that on the known to fix list posted last night.

> there are points where nothing happens - I can't work out why that might be the case.

This happens when the following two conditions occur:

a. CTe == last IPS of a run (or segment if it has been made into one)
b. CTe-CTs < time gap before next IPS.

In this case, the next selected time period, which has the same duration as the current, falls in empty space with 0 samples. This happens most commonly when the selected time duration is small, like at the letter level, so when you run into a gap that has a duration > the selection (like between two words), then the currently logic selects 'empty space', which == 0 samples, which == app does nothing on the action.

Your suggestion as part of solution for 2nd issue:

> NTs = First IPS time where (IPS time > CTe)

will fix this first issue.

> The selection slowly shrinks in size across multiple jumps. 

The issue here is that each advance can result in the number of selected samples < number of previously selected samples. If this happens many times in a row, the selected time period duration shrinks and shrinks until the selection period is only 1 sample in duration.

> I can see why that happens. I think the following fixes it:
> NTs = First IPS time where (IPS time > CTe)
> NTe = NTs + ( CTe-CTs)

This will not fix this second issue since it does not change the conditions where the number of selected samples shrinks smaller and smaller based on the pattern of IPS runs vs ZPS (zero pressure samples) or time gaps in the sample stream.

I think the only way to keep this from happening is to also ensure the sample count is also maintained. i.e:

NTe_temp = NTs + ( CTe-CTs)
NTe = max(NTe,   First IPS time where (IPS time > NTe))

I'm going to work on fixing these issues now...

**Comment by Mark-Torrance** [comment]
Good. I'll leave this with you. I think this is one of those (many) situations where it takes more effort talking about the fix than actually fixing it. The issues will be as apparent to you as they are to me. Thanks for bearing with me.

Please also don't let this spill over into your next project (i.e. I'm expecting you to stick to the 1st May deadline). Even with no additional fixing I'm very pleased with what we have.

**Comment by isolver** [comment]
@Mark-Torrance 
OK, I think I have the logic for 'Advance Selection' / ' jump forward' working so that both issues are fixed (action not advancing, repeated advances causing shrinking of selection to 1 sample).

I committed the changes. If you have time now, could you check that the advance forward logic now works as you think makes sense as well. If so, I will apply the same changes to the 'skip back'  action.

**Comment by isolver** [comment]
I have gone ahead and applied the same thinking to 'Jump backward' as I did for 'Jump Forward'. Seems that both now work in a reasonable way. Let me know if you find otherwise.

@Mark-Torrance : So if the actions are now OK, we need to assign final shortcut keys to the 6 selection manipulation actions. Please let me know what you think they should be. 

I guess the question of whether the 2 start point movement actions are useful enough to keep, or should be removed, should be answered (by you) as well. I like them. ;)

**Comment by Mark-Torrance** [comment]
Ok, keep the start point movements. 

What about this...?
- left,right for jumps (can you map to these without modifiers?)
- CTRL+left,right for move end
- ALT+left,right for move start

**Comment by isolver** [comment]
Just did a commit with the shortcuts you suggested.

Let me know if you think they should be changed after you take it for a spin. Thanks Mark.

**Comment by Mark-Torrance** [comment]
Great. Thanks. I just need to finish a job, then say hi to the kids, then I’ll have a look.

Mark

**Comment by Mark-Torrance** [comment]
This is working almost perfectly now, and makes markup very quick.

One remaining issue that I can see: if you...

Position sample so that either or both of Ts and Te are not at a sample (i.e. are in blank space on the timeline) and between them is a single trace (a sequence of IPS samples with no nonIPS except the one at the end).

![capture](https://cloud.githubusercontent.com/assets/3226576/7417394/b64a64da-ef5d-11e4-8052-fd26ca904814.PNG)

Then try the "move Te back" action (to bring Te to last sample of trace) or the "move Ts forward" action (to bring Ts to the first sample of the trace). In both cases you get the "Te =Ts" error.

The autotrim that occurs when you open the tagging dialogue sorts this, except when the selection (before moves) is an illegal tag (as in the example above).

With a bit of button pressing you can get round this, so it's not a huge issue, but it would be nice to fix it it you have time.

**Comment by isolver** [comment]
"move Ts forward" action fixed

**Comment by isolver** [comment]
> "move Ts forward" action fixed

I take that back; both ""move Te back" and "move Ts forward" actions do not work correctly. Not just in the case you gave, but if you do > 1 of each action in a row, it fails all but the first time.

Will have to look into fixing this tomorrow, Friday. Sorry.

**Comment by Mark-Torrance** [comment]
> I take that back; both ""move Te back" and "move Ts forward" actions do not work correctly. Not just in the case you gave, but if you do > 1 of each action in a row, it fails all but the first time.

I can't reproduce this - works great for me. So if it's happening for you it's due to changes that you've just made.

**Comment by isolver** [comment]
Yup, I reverted back one revision and the only issue is the one you raised. Will work on it Friday.

**Comment by isolver** [comment]
@Mark-Torrance:  I committed a fix for these 2 issues. Let me know fi things are looking good from your end. 

If so, I'll bump the version number up and do a rebuild of the exe version. 

I guess we need to determine where the exe version of the app should live and give a download URL for it on the project page??.

**Comment by Mark-Torrance** [comment]
Hi Sol,

Sorry for the delay. Fix works perfectly.

If you could create an exe and put it on google, I’ll sort out a better link for it.

Thanks again for the massive effort that you’ve put into this. I think we should (mainly you) should be proud of the results.

Mark
