### ISSUE TITLE
Sample event times should be corrected for polling rate

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#61]
ISI should match that of the device time stamps.

**Comment by isolver** [comment]
Or, also test if the PACKET event times are stable enough that an offset and gain can be calculated to allow conversion from PACKET time -> iohub time for sample events

**Comment by isolver** [comment]
Updated: Now, a pen sample time is calculated by:

```
# Calculate iohub time for a pen sample event using event's
# native timestamp. 
#
# cs_iotime: current pen sample iohub time
# cs_hwtime: current pen sample event native / hw timestamp
# s1_iotime: Time iohub received first pen sample after starting to record events.
# s1_hwtime: Native event timestamp for first pen sample received when record events started.

cs_iotime = s1_iotime+(cs_hwtime - s1_hwtime)

```

Advantages:
- iohub times for events are always separated by the ISI interval 

Disadvantages:
- it seems that at least with the wacom device, the native event timestamp time base drifts relative to the iohub / experiment time base by about 1 msec every 2 minutes or so. This may lead to timing accuracy issues for long recording periods.

Leaving issue open so that more thought can be put into a better way to convert from native event timestamp -> iohub time base during experiment runtime.

As long as polling interval is small relative to device sampling rate, an obvious other option would be to simply:

```
cs_iotime = current_iohub_time -  confidence interval / 2.0
```

This would result in drift between time bases not being an issue, however the iohub event times dt between samples will not be a constant, varying by up to an amount just less than the polling interval being used.

**Comment by Mark-Torrance** [comment]
> it seems that at least with the wacom device, the native event timestamp time base drifts relative to the iohub / experiment time base by about 1 msec every 2 minutes or so. This may lead to timing accuracy issues for long recording periods.

These get synchornised again at the start of a trail? If so then I don't think this drift is an issue at all. There is no situation, for example, where we would require highly accurate times from stimulus onset or start or trial for very long writing periods. All that is important is that ISI is accurate.

**Comment by Mark-Torrance** [comment]
> cs_iotime = s1_iotime+(cs_hwtime - s1_hwtime)

Is using s1 time here essential (I might have missed something). It would make analysis quite a bit easier if time is from trial onset.

**Comment by isolver** [comment]
This is for converting / calculating the time of a pen sample in
iohub/psychopy time based on the time stamp provided in each sample from
the win tab driver.

s1_ times are based on the first sample received after last starting pen
event recording.

Since iohub event times are in the same timebase as the clock used by
psychopy, you can directly compare experiment event times, like trial
onset, a graphics change (flip) time, etc, with device event times.

**Comment by Mark-Torrance** [comment]
Sure. I understand. Just from a MarkWrite analysis point of view I think it makes more sense for time to run from trial start, but we can easily create that as a first step in MW. Minor point, anyway.

**Comment by isolver** [comment]
From an report output or even user gui field POV, what you are suggesting is not an issue. 

Internally though, we need to keep the basic assumption that all samples read from a file contain unique, non overlapping times that increase monotonically throughout the data set. This is core to how all segmentation / grouping is done in MarkWrite. It is also used to quickly identify invalid segment candidate regions due to temporal overlap with an existing segment within the same segmentation level of the hierarchy.

**Comment by Mark-Torrance** [comment]
Good. Thanks.

**Comment by isolver** [comment]
marking as fixed. Can be reopened if any issues are found during beta usage.
