### ISSUE TITLE
Pen Calibration Integration ... ???

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#74]
See email from Guido:

https://drive.google.com/open?id=1bz2SjxjxQhIYnUdP_WliudxkmjkNk1zyQtdGbuW2v9MXXCszR2UtOE-d4sAkaIpqfGsmZsCBb8fsknbV

**Comment by g-no** [comment]
Closed here, see issue [https://github.com/isolver/OpenHandWrite/issues/78].
