### ISSUE TITLE
Create example Psychopy Builder Project that uses iohub.wintab device

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#76]
Email exchange:

"Code components" can be added in a Builder project, where you can run any bit of python code at the point you add the Code Component to your experiment timeline.
This is what is done now for the eyetracker Builder demo ( psychopy\demos\builder\iohub\stroop_eyetracking\stroop.psyexp ).

So this is a middle ground approach that we could have an example of doing, and would not take too much time to do.

MT: Good. Let add creating a similar demo as a high priority todo. I think something like this is pretty essential. This is sort of what I had pictured – though didn’t articulate - when we talked initially about a template experiment.

**Comment by isolver** [comment]
Note that this will only really be useful when the latest iohub code is merged with the PsychoPy project repo, so a user can download and install the STandalone PsychoPy App / Env. that has the iohub.wintab device code in it.

SO I will make an example in the psychopy.demos.builder.iohub folder and include this in the Pull Request I make to PsychoPy/PsychoPy github repo.

I will likely not made this pull request until I know that the wintab device api and events fields are at least close to what Mark and Guido expect from it. As well that it is unlikely for us to make backwards incompatible changes to the wintab device / events.

**Comment by Mark-Torrance** [comment]
Good. So high priority (Guido do you agree?) but leave-until-end.

**Comment by isolver** [comment]
More thoughts on requirements for this:
- [x] initialize iohub with wintab device support enabled
- [x] start / stop saving / streaming of events
- [x] Using wintab events at runtime. 
- [x] Writing DVs to iohub hdf5 file.

**Comment by Mark-Torrance** [comment]
I've ticked all of the above. Here is bit from my email of just now:

I hope that this is just an adaptation of what you’ve already done and doesn’t mean starting again. If so, I’m really sorry that I didn’t think this through before. I do think that something like this is pretty essential, though. A useful simple template would just be something like Welcome screen > trials (more than one) > Goodbye screen. Trials: show text of word > subject writes word > subject pen-presses in area of tablet to continue when finished. Text display disappears at first pen press (i.e. writing onset). I could imagine myself then using this, and the more complex TemplateExperiment, to then work out how to do most other things.

**Comment by isolver** [comment]
If we keep the Builder example really simple, just as you have outlined,
then this is not a big issue. 2-3 hours of work should get something banged
out.

**Comment by isolver** [comment]
SO template should simply:
1. Welcome screen
2. trials (more than one)  based on experiment_conditions file
   
   a. show text of word 
   b. Text display disappears at first pen press (i.e. writing onset).
   c. subject writes word 
   d. subject pen-presses in area of tablet to continue to next trial
3. Exp finished screen

**Comment by isolver** [comment]
Implemented in last OHW distro release. closing..
