### ISSUE TITLE
Add runtime fields to wintab sample events

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#79]
Runtime Only:
- [x] velocity (x, y, xy)
- [ ] acceleration(x, y, xy)

Saved and Streamed:
- [x] status field

**Comment by isolver** [comment]
- Implemented 'status' field. It is saved to the hdf5 file as a uint8
- at runtime it is converted (and therefore accessed by the user) to the string name of the constant

Possible Values:

```
    # A sample that is the first sample following a time gap in the sample stream
    STATES['FIRST_ENTER'] = 1
    # A sample that is the first sample with pressure == 0
    # following a sample with pressure > 0
    STATES['FIRST_HOVER'] = 2
    # A sample that has pressure == 0, and previous sample also had pressure  == 0
    STATES['HOVERING'] = 4
    # A sample that is the first sample with pressure > 0
    # following a sample with pressure == 0
    STATES['FIRST_PRESS'] = 8
    #  A sample that has pressure > 0
    # following a sample with pressure > 0
    STATES['PRESSED'] = 16
```

@g-no & @Mark-Torrance : please let me know if the constants need to be changed or if they are OK as is.

**Comment by Mark-Torrance** [comment]
Well, there are eight possible transitions (conveniently?): OoR is out of range (so following time gap)
OoR->Hovering STATES['FIRST_ENTER_hover']
OoR->Pressed STATES['FIRST_ENTER_pressed']
Hovering->Hovering STATES['HOVERING']
Hovering->Pressed STATES['FIRST_PRESS']
Pressed->Hovering STATES['FIRST_HOVER']
Pressed->Pressed STATES['PRESSED']
So I think just need to split your First_Enter state (though my guess is that 'FIRST_ENTER_pressed' never happens).

**Comment by isolver** [comment]
> OoR->Hovering STATES['FIRST_ENTER_hover']
> OoR->Pressed STATES['FIRST_ENTER_pressed']
> Hovering->Hovering STATES['HOVERING']
> Hovering->Pressed STATES['FIRST_PRESS']
> Pressed->Hovering STATES['FIRST_HOVER']
> Pressed->Pressed STATES['PRESSED']

So there are 6 status values wanted, with the extra one coming from having
2 types of FIRST_ENTER_x states instead of 1.  Is that right? Good with you
as well Guido?

(though my guess is that 'FIRST_ENTER_pressed' never happens).

I've been hammering on the wacom device and if you really quickly 'hit -
drop' the pen onto the surface it will go from OOR->Pressed on the first
sample about 50% of the time. I guess if the sampling rate was more than
120 Hz the likelihood of this would drop greatly. (No pun intended).

**Comment by Mark-Torrance** [comment]
Sorry, yes, six, not eight. I realised that you can't have -> OoR transitions (obvs) but then forgot to edit.

**Comment by isolver** [comment]
On Thu, Nov 12, 2015 at 6:08 AM, Mark-Torrance notifications@github.com
wrote:

> I realised that you can't have -> OoR transitions

You could mark last sample before a gap in sample times, which would be
xxx->OoR I guess,  but this would require delaying the output of each
sample, so IMO would be better to leave as a thing for in MarkWrite it is
is needed.

**Comment by Mark-Torrance** [comment]
Agreed. And v easy to do in MarkWrite.

**Comment by g-no** [comment]
What about
Hovering->OutOfReach? (This happens only rarely during word writing but often in text production; you'll want to collect the time between Hovering->OoR and OoR->Hovering (or OoR->Pressed, if that's possible).
Pressed->OoR may be added as well but will be extremely rare

**Comment by Mark-Torrance** [comment]
Because as things stand the tag is on the second sample in transition and in -> OoR transitions the second sample does exist. We could create a new variable for the first in the pair (so for sequence-terminal events) but the argument is that this is only really useful in analysis, so better done in MW than at runtime. Or that's how I see it.

**Comment by isolver** [comment]
So the -> OoR transition types should be added to the list of sample status
constants so the list is technically 'complete'.

However:
- we will not populate samples with ->OoR status fields during experiment
  runtime, since it would add an extra sample lag.
- we will update the samples that should have an ->OoR status as part of
  the hdf5 loading process into MarkWrite.

Do I have this right?

**Comment by Mark-Torrance** [comment]
I suggest that we load the hdf5 file without adding any more variables (so as it is loaded at the moment). We then add these, and any other variables, as needed as part of the post-markup analysis process. So...
- we will not populate samples with ->OoR status fields during experiment runtime, since it would add an extra sample lag. 
- we will **not** update the samples that should have an ->OoR status as part of the hdf5 loading process into MarkWrite.
- we will make sure that the functionality is there for naive users (aka Mark) to add variables of this sort as part of the the post-segmentation data analysis process in SegmentLevelReportExporter

**Comment by isolver** [comment]
I made changes to the sample status fields, but when doing it I realized there was a different way to achieve the same result, while keeping the current set of 5 status codes. Let me know if you think the following is fine or better than what we agreed. If you like the original plan better, I can change it to that easily.

So status codes are as before:

```
    # A sample that is the first sample following a time gap in the sample stream
    FIRST_ENTER = 1

    # A sample that is the first sample with pressure == 0
    # following a sample with pressure > 0
    FIRST_HOVER = 2

    # A sample that has pressure == 0, and previous sample also had pressure  == 0
    HOVERING = 4

    # A sample that is the first sample with pressure > 0
    # following a sample with pressure == 0
    FIRST_PRESS = 8

    #  A sample that has pressure > 0
    # following a sample with pressure > 0
    PRESSED = 16
```

but FIRST_ENTERED is always combined with either  FIRST_HOVER or FIRST_PRESS.

So in runtime code, a sample streams status values might look like:

```
time: 2.000    status: [FIRST_ENTERED, FIRST_HOVER]
time: 2.008    status: [HOVER]
time: 2.015    status:  [FIRST_PRESS]
time: 2.023    status: [PRESS]
time: 2.030    status: [PRESS]
time: 2.038    status: [PRESS]
time: 2.045    status: [FIRST_HOVER]
time: 2.053    status: [HOVER]
time: 2.060    status: [HOVER]
```

This way you can check for FIRST_PRESS or FIRST_HOVER samples regardless of whether it is also the first sample or not without needing to check for 2 possible values:

```
is_first_press_sample = 'FIRST_PRESSED' in sample.status
is_first_hover_sample = 'FIRST_PRESSED' in sample.status
```

or check if a sample is the first since a time gap, regardless of whether it is hover or pressed pressure, by checking only 1 status value:

```
is_first_sample_since_gap = 'FIRST_ENTERED' in sample.status
```

Is this OK, or would you rather having the extra status code type?

**Comment by Mark-Torrance** [comment]
That sounds fine to me.

**Comment by Mark-Torrance** [comment]
Just thinking about output variables. We will need (I think) a "static" code indicating pen currently not moving. With not moving defined as within a period of n sample such that trace length between s and s-1 < d. for samples 1 to n. This could usefully be added here? So we append STATIC to some HOVER and PRESS states.

**Comment by Mark-Torrance** [comment]
Though, thinking again, this might be best done as part of the segment / sample data post-processing (to get output variables) because we might want easy manipulation of n and d thresholds.

**Comment by Mark-Torrance** [comment]
Sorry to return to this again. Can we simplify things further by specifying PRESS and HOVER for all PRESS and HOVER events.

So instead of

> time: 2.000    status: [FIRST_ENTERED, FIRST_HOVER]
> time: 2.008    status: [HOVER]
> time: 2.015    status:  [FIRST_PRESS]
> time: 2.023    status: [PRESS]
> time: 2.030    status: [PRESS]
> time: 2.038    status: [PRESS]
> time: 2.045    status: [FIRST_HOVER]
> time: 2.053    status: [HOVER]
> time: 2.060    status: [HOVER]

we have 

time: 2.000    status: [HOVER, FIRST_ENTERED, FIRST_HOVER]
time: 2.008    status: [HOVER]
time: 2.015    status:  [PRESS, FIRST_PRESS]
time: 2.023    status: [PRESS]
time: 2.030    status: [PRESS]
time: 2.038    status: [PRESS]
time: 2.045    status: [HOVER, FIRST_HOVER]
time: 2.053    status: [HOVER]
time: 2.060    status: [HOVER]

Just simplifies things a bit if you want to, for example, just filter out all non-inking sequences.

**Comment by isolver** [comment]
closing and will open specific bug for requested change to sample status field.
