### ISSUE TITLE
Time line label units: ms -> s

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#89]
Utlra-trivial: Timeline scale is in seconds not ms so label needs changing.

**Comment by isolver** [comment]
This was a by product of the issue with dividing hdf5 sample times by 1000, so should now be fixed in github code.

**Comment by Mark-Torrance** [comment]
Not sure it was (and I wasn't clear). The axis label for the timeline says ms - presumably hard coded in - and should say seconds. I said it was ultra-trivial :)

**Comment by isolver** [comment]
On Fri, Dec 4, 2015 at 10:44 AM, Mark Torrance notifications@github.com
wrote:

> axis label for the timeline says ms - presumably hard coded in - and
> should say seconds. I said it was ultra-trivial :)

It says sec for me now, and I hope for you too when you get the update. ;)

The axis auto scale based on the value type specified and the actual data
range, so while it has always been set internally to 'sec', it can switch
to msec if all the values are very small, like in the case of data that is
between 0 and 20.0 incorrectly being dividing by 1000.0.

**Comment by Mark-Torrance** [comment]
Ah, clever. Good. Sorted then.

**Comment by isolver** [comment]
I hope. ;)
