### ISSUE TITLE
Add 'auto pan/zoom' mode for segment selection in project tree

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#9]
Add an "Auto Zoom" stateful button to app. 

If enabled, when user selects segment node in tree panel, then the temporal and spatial view widgets should change their pan and zoom settings so that selected segment data is zoomed as much as possible to fill both views. 

If disabled, use current functionality.

**Comment by Mark-Torrance** [comment]
Spatial view = segment view? If so, this is good. I suggest don't zoom the overview.

**Comment by isolver** [comment]
The View names I've started normalizing to are as shown in the attached
image.

![writemark_view_dock_names](https://cloud.githubusercontent.com/assets/1795082/7068743/773bd542-dea2-11e4-9356-0127f61a71c5.png)

Based on these View names, I think both the Temporal and Spatial Data views
would be zoomed since, as I understand it, a reason for this requirement is
to make it easier for the user to select the correct pen point sub sets to
create child segments.

Please let me know.

**Comment by Mark-Torrance** [comment]
I can't see the image. If Spatial Data = where you see lots of text rather than the current segment
then yes, you're right. Sorry, I wasn't thinking straight.

My suggestions for names are
Timeline (for temporal)
Overview (for Spatial Data)
Segment view (for the view of the currently selected segment)

Your names are more precise but quite a few users will be people without much of a grasp of underlying ideas etc (think school teachers doing an MA project as a target users).

**Comment by isolver** [comment]
I updated the comment and added the image. Linking here as well.

![writemark_view_dock_names](https://cloud.githubusercontent.com/assets/1795082/7068743/773bd542-dea2-11e4-9356-0127f61a71c5.png)

The names I like are:
- Temporal Data View
- Spatial Data View
- Selected Data View

Reasoning:
- Both 'Temporal Data View' and 'Spatial Data View' can be 'Overviews', or then can not, depending on the zoom / pan the use has applied. That is why I now find using the word 'Overview' confusing / misleading.
- Selected Data View shows the selected segment data when a segment is selected, but it also spatially shows the pen data points currently selected by the Temporal View Selection Region when a user is in the process of selecting points for a /potential/ segment that has not yet been created. That is why I now find using the word 'Segment' in this view confusing.

What you think about this? ;)

**Comment by isolver** [comment]
Maybe to refine / shorten my suggested view names:
- Temporal Data View -> Temporal View
- Spatial Data View -> Spatial View
- Selected Data View -> Selected Data

**Comment by Mark-Torrance** [comment]
OK. Can we have timeline instead of temporal view? I agree with the (shortened form) other two.

**Comment by isolver** [comment]
Agreed 'Timeline' is better than 'Temporal View' for sure; thanks for the
idea.

**Comment by isolver** [comment]
What about the 'Project Details' Dock. Should that just be called "Segments" or "Segmentation" or something? Or just leave it for now. ;)

**Comment by Mark-Torrance** [comment]
Markup Tree? It would be good to remove the Project Details title.

**Comment by isolver** [comment]
- [x] Project Details -> Markup Tree

**Comment by isolver** [comment]
duplicate of #28 now. closing
