### ISSUE TITLE
Add avbin.dll to OpenHandWrite distro and update windows path env variable.

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#93]
Right now, unless avbin.dll happens to be installed on the PC separately, users always get the error

ERROR avbin.dll failed to load.
                     Try importing psychopy.visual as the first library
                     (before anything that uses scipy)
                     and make sure that avbin is installed.

**Comment by g-no** [comment]
seems to be solved ?

**Comment by isolver** [comment]
I think so, I do not see the warning; will close for now.
