### ISSUE TITLE
Creating trial segments when loading data from iohub hdf5 file

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#95]
Sol writes:

> I'm doing this now, it is mostly done. If an iohub hdf5 file is loaded, and the hdf5 file has a condition_variables table in it, then a dialog is displayed like that shown when the hdf2txt script is run. The start and end trial time column names selected by the user in this dialog are used to get the start, end time pairs that are used to trim non-trial samples and to create the trial segments.
> 
> I'd like to get input on some of things so I know how far to go with this:
> 1. In the hdf2txt script, I filter the variable/column names that are shown by only showing those that start with 'DV_'. The start time list is further filtered by including variables that end in '_START'.The end time list is further filtered by including variables that end in '_END'.

MT: As side note: I can see hdf2txt being really useful for batch-processing raw data files, completely bypassing markwrite. If, for example, you just want response time and writing duration then there's no need for markup.

> Q: Should the same filtering be done in the MarkWrite app when showing the trial time period selection dialog? If yes, should the filter values used be made app settings, or can they stay fixed and users just need to know how to name their DV columns that will be used for trial time selection?

MT: I think they can remain fixed. Very intuitive to use the DV etc tags in the trial datasource file (or whatever we call it)

> 1. Right now, the pen sample list for each trial are literally converted to segments. This means that in the temporal and spatial view's, all sample data is visible, with a selected trials samples colored green. 
> 
> Q: Is this OK? I get the feeling that it would be nice, maybe necessary, to be able to 'hide' samples that are not within the currently selected trial. Otherwise, there is tons of pen point 'noise' in the spatial view because of all the trial by trial data. What do you think? 

MT: Yes, I think this is essential. One way of doing this is have the spatial view only show the top-level parent of the selected segment. When importing data that does not have trial information, create a top level segment that includes all of the samples.

> If you agree that some form of pen sample range visibility filter needs to be created, it could be:
> 1.  fixed to trial level only, to only switch when a different trial segment is selected,
> 2. generic to any segment, so it could be applied at any level of the segment hierarchy, not just at the trial level. 
> What do you think?

MT: So I'm suggesting something like 1, but a bit simpler. You just show the top parent of whatever segment is selected (which of course could be at the top level, and will be when you first start markup because there won't be any other segments yet).

**Comment by g-no** [comment]
> One way of doing this is have the spatial view only show the top-level parent of the selected segment.

Yes, that's good and necessary.

**Comment by Mark-Torrance** [comment]
There are some more general spatial view zooming issues that you (@g-no ) raised in https://drive.google.com/open?id=0B4Hx60i6a-Q-bDMxNWhVU2hwZVU  I'll start a new, very general, issue for this.

**Comment by isolver** [comment]
Note that there is a bug in the version of MarkWrite you have that divides all pen sample times by 1000 when reading from an hdf5 file. For the other supported input file types, times are in msecs and were converted to sec.msec format when read into markwrite. This was wrongly being applied to hdf5 data as well. 

This is now fixed. I will send an update early next week once I get the a) trial segmentation, b) limiting of visible data in spatial view, c) and hopefully data filtering and velocity calculation stuff all completed.

**Comment by isolver** [comment]
Issue in adding the spatial view data range filtering, input on best way you see to handle this from a usability POV would be helpful.

Assume that the spatial view data is limited to only include data within the 'active' top level segment (trial). Issues:

1) The timeline view, which is not filtered based on the active segment, still allows a user to move the selected data region partially or fully outside the the top level segment. The selected data region could be over > 1 top level segment, over data that has no top level segment yet, or both.

If we try to solve this by also only displaying data in the timeline view that is in the current segment, then we run into a bunch of issues related to 'how do you create segments in the first place'. So this is not a solution.

2) In the case of the timelines selected data region including >1 top level segments, what gets displayed in the spatial view?

3)  In the case of the timelines selected data region moving to a completely different top level segment, I guess we could make markwrite detect this and change what the 'active' top level segment is, thus updating the spatial view data to the new trial.

4) If this feature is going to be generic, and be used with data files that have no top level trial segments, we need to figure out how to handle the cases of the timeline selected data region being over data that has not top level segment, or is partially over unsegmented data.

Without functionally consistent solutions to the above, then:

> You just show the top parent of whatever segment is selected (which of course could be at the top 
> level, and will be when you first start markup because there won't be any other segments yet).

can not be implemented as stated without causing a bunch of usability issues

I'm going to halt working on this particular feature request until we agree on how to hand this.

**Comment by Mark-Torrance** [comment]
Before I comment on the rest: Is this..

> If we try to solve this by also only displaying data in the timeline view that is in the current segment, then we run into a bunch of issues related to 'how do you create segments in the first place'. So this is not a solution.

Really not a solution? The timeline needs to show the top-parent of the current segment. If top-parent is always created when data are imported then this will always exist. So for "GetWrite" created files these top level segments will be trials. For data without trial tags, automatically create a single top-level segment that includes the whole data file (Which you can call Trial 1). Doesn't that sort it?

**Comment by isolver** [comment]
> The timeline needs to show the top-parent of the current segment.

For the spatial view, for sure. For the timeline view, are we sure about
that? The timeline scale, zoom, and panning functionality already handles
the type of issue we are trying to fix in the spatial view: remove from
visibility a bunch of data that  is just a distraction for the current task.

> So for "GetWrite" created files these top level segments will be trials.

I'm not sure we can assume this will always be the case. It depends on
whether the experiment was written to save out DVs to the condition
variable table that can be used to segment the data into trials. There is
no way to force someone to do this when they make their experiment. Not
everyone will do this; even if we say they should.

I think the python experiment example does this, but the
builder experiment does not, for example.

For data without trial tags, automatically create a single top-level

> segment that includes the whole data file (Which you can call Trial 1).
> Doesn't that sort it?

I'm not sure it does. Right now, data files without trial segmentation
already have a 'top level' node in the tree, being all unsegmented data. If
we always make all data be in an artificial trial 1, then a) this may seem
confusing to a user and b) there would never any unsegmented data. Would
this not cause issues for people not using trials who want to know what
data is yet to be segmented?

If I am over complicating things here, which I am known to do, let me know
and I can do as you suggested; it is the easiest solution to add / a
'quick' fix. I'm worried it is going to cause more issues than it solves.

**Comment by Mark-Torrance** [comment]
> >  The timeline needs to show the top-parent of the current segment.
> > For the spatial view, for sure. 
> 
> For the timeline view, are we sure about
> that? The timeline scale, zoom, and panning functionality already handles
> the type of issue we are trying to fix in the spatial view: remove from
> visibility a bunch of data that  is just a distraction for the current task.

Agreed, but I can't see any situation where you would want multiple trials in the same timeline. In fact, quite the opposite. So unless I'm missing something, yes, I'm sure.

> > So for "GetWrite" created files these top level segments will be trials.
> 
> I'm not sure we can assume this will always be the case. It depends on
> whether the experiment was written to save out DVs to the condition
> variable table that can be used to segment the data into trials. There is
> no way to force someone to do this when they make their experiment. Not
> everyone will do this; even if we say they should.
> I think the python experiment example does this, but the
> builder experiment does not, for example.

Ok, but if they don't then they are silly. Which is true for any experiment. We might want it to be possible to read top-level segment data from txyp files, which would allow manual addition of trial data for people who didn't plan their experiment properly (and potentially for data collected by something other than GetWrite). But I would put this as a Priority 2 enhancement rather than see it as essential.

> > For data without trial tags, automatically create a single top-level
> >  segment that includes the whole data file (Which you can call Trial 1).
> >  Doesn't that sort it?
> 
> I'm not sure it does. Right now, data files without trial segmentation already have a 'top level' node in the tree, being all unsegmented data. If we always make all data be in an artificial trial 1, then a) this may seem confusing to a user and b) there would never any unsegmented data. Would this not cause issues for people not using trials who want to know what data is yet to be segmented?

This puts you in the same situation as you would be if, for example, you created sentence level segment and then divided into words (i.e. you'll very often be segmenting at below top level anyway). Also, even in "just write me an essay" sort of research I would expect to have more than one trial, with an initial practice trial. So this is only really an issue for data brought in from other programs. I think we should worry about our own data first.

**Comment by isolver** [comment]
OK, so to flush out the functionality changes and implications, does this
cover things:

1) Add a markwrite project setting that enables / disables filtering of
data based on level 1 segments.
    a) Can only be changed in the settings for a new project prior to
loading the data file.
    b) If enabled, both timeline and spatial views will be limited to
current L1 segments start / end time.
    c) If not enabled, current functionality.

2) When data is loaded into a new project and L1 segment filtering is
enabled:
    a) There will never be 'unsegmented samples'.
    b) L1 segment(s) can never be deleted.
    c) If it is an hdf5 file that trials can be segmented from we do so
    d) If trials can not be inferred using the loaded file, we create a
single L1 segment that covers all the data in the file, and call it "All
Data".
    e) The only way for a user to see data outside the current L1 segment
(trial in this case), is to select a node from the segment tree view that
is either:
          i) a different L1 segment
          ii) the child of a different L1 segment.
    f) This implies that if a single 'All Data" was created when the data
was imported, the user will always see all data in the temporal and spatial
views, as is the case now.

Thanks again.

**Comment by Mark-Torrance** [comment]
This is all fine. But (and I don't know why this wasn't obvious before): Why not skip (1) and set L1 segment filtering as True if input file has trial data and False if not. As you point out in 2f, creating and All Data segment just creates a redundant L1 layer.

**Comment by isolver** [comment]
On Mon, Dec 7, 2015 at 11:01 AM, Mark Torrance notifications@github.com
wrote:

> This is all fine. But (and I don't know why this wasn't obvious before):
> Why not skip (1) and set L1 segment filtering as True if input file has
> trial data and False if not. As you point out in 2f, creating and All Data
> segment just creates a redundant L1 layer.

Only because I imagine (and that is all it is) some people may like the way
markwrite currently works, allowing you to
- leave sections of data unsegmented
- remove / change L1 segments

If this is just my imagination, and not a real use case, I agree with your
suggestion of removing 1).

**Comment by Mark-Torrance** [comment]
Ok what about:
- Include a segment_by_trial_when_possible setting
- If no trial variables, existing behaviour.
- If trial variables, if setting segment-by-trials then segment by trials, else existing behaviour

No idea why you might not want to segment by trials, but at minimum looking at it's behaviour when you don't is a good tutorial in why it's necessary. So add the setting (if easy).

**Comment by isolver** [comment]
Sounds like a plan. Thanks.

**Comment by isolver** [comment]
Have committed updated code that implements all aspects of this ticket.

Known minor issues:
- when a trial segment is selected, all data in the trial is selected (i.e. timeline's selected data region is set to segment start - end, which in this case is the full trial.). Not sure what to do about this, if anything 
- when the selected data region is moved in the timeline view, the 'trial segment' becomes deselected in the segment hierarchy. This is required so that data about the selected region can be displayed in the properties table. However, this currently also means that you have no way to see what trial's data is being displayed in the views. This does need to be addressed, but best way to do so is not clear, so leaving it as is for now.

@Mark-Torrance , if you agree, I will close this change request and open two lower priority bugs related to the two issues mentioned above.

**Comment by Mark-Torrance** [comment]
agreed. 

One possible solution to the second issue would be to identify the L1 segment associated with the (start of then) current selection and add that to the properties (displaying it at the top of the properties window)?

**Comment by isolver** [comment]
On Tue, Dec 8, 2015 at 10:57 AM, Mark Torrance notifications@github.com
wrote:

> One possible solution to the second issue would be to identify the L1
> segment associated with the (start of then) current selection and add that
> to the properties (displaying it at the top of the properties window)?

Agreed. Definitely the quickest thing to do for now; maybe not the best
user interface design solution, but that can be worried about another day.

**Comment by isolver** [comment]
Closing. Added issues #99 and #100 to cover the two issues mentioned above.
