### ISSUE TITLE
'Trial' segment data selection behaviour 

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#99]
Following  addition of features defined in #95 ,when a trial segment is selected, all data in the trial is selected (i.e. timeline's selected data region is set to segment start - end, which in this case is the full trial.). 

Not sure what to do about this, if anything

**Comment by isolver** [comment]
Can maybe detect when it is a 'trial' l1 segment being selected and if it is:
- if there are segments within the trial, set selection region equal to first segment start/end time
- if there are no segments, set selection region equal to the trial's first pen sample series.

**Comment by Mark-Torrance** [comment]
I think current behaviour makes sense. I wouldn't change it. But (and this probably should be another issue) - it's impossible to grab the end point in timeline when it is beyond the end of the current zoom. When end of selection = end of zoom, it's grabbable but not visible. Not normally much of an issue but it is if selection, zoom, and trial are all the same span. 

Possible fix would be to zoom such that maximum is trial-duration*1.05? Suggest fix if quick but delay to next milestone if not.

**Comment by isolver** [comment]
Ya, I've noticed this too. Should have created an issue for it.

If there is a delay between trials, the plot bounds could be set to be in
between trials, this should fix the issue without displaying any data from
another trial. If there is no delay between trial1 end and trial2 start,
then this would not work, as data from 2 or three trials would become
visible.

**Comment by Mark-Torrance** [comment]
And also there might bot be any samples in the added-on-time. I guess need to make the timeline not quite extend to the border of its window, then.

**Comment by isolver** [comment]
I think the root issue is in the pyqtgraph library. When a plot region
extends to the last data point in the graph view, the plot regions end line
is not drawn in the plot window.

I'll try and fix the root issue, otherwise I will do a work around of some
sort. ;)

**Comment by isolver** [comment]
I somewhat fixed this by making the selection region left / right side lines thicker. This seems to allow you to press on the very inner edge of the timeplot view when there is a selection region covering a full trial, and drag in to move the end of the selection region.

**Comment by Mark-Torrance** [comment]
Somewhat fixed is good! And actually a secondary effect of this is that grabbing that region now become easier generally. I can't see any disadvantages of this (that aren't simply solved by users zooming in).

**Comment by isolver** [comment]
Closing this as original ' issue' reported is not considered an issue, and the moving of selected region end line when full trial is selected has been fixed as best I can tell.
